### ISSUE TITLE
خطای سرور  در انتخاب ایتم پنج بعنوان سرور خارج

### ISSUE THREAD

**Issue by sajadshadmn** [Azumi67/Chisel_multipleServers#1]
![IMG_9865](https://github.com/Azumi67/Chisel_multipleServers/assets/122069332/14c38534-6ba5-400a-8d73-1c878841a89a)

**Comment by sajadshadmn** [comment]
تمام اسکریپتها رو هم امتحان کردم
روی سرورهای دیگه هم از همین دیتا سنتر تست کردم اما همین ارور رو میده

**Comment by Azumi67** [comment]
سلام. میشه دوباره اسکریپت chisel رو تست کنید و همینجا بهم اطلاع بدید تا بقیه هم درست کنم . مرسی

**Comment by sajadshadmn** [comment]
اوکی شد
ممنون
![Uploading IMG_9867.jpeg…]()

**Comment by sajadshadmn** [comment]
![IMG_9867](https://github.com/Azumi67/Chisel_multipleServers/assets/122069332/360486d9-c916-4af5-9a3f-e0dc5d42bcce)

اوکی شده
ممنونم واقعا

**Comment by sajadshadmn** [comment]
سلام
سپاس از زحمات شما
روی حالت پنج با دوتا سرور خارج که انجام دادم پینگ خیلی بالا بود در حدی که به جز اینستا واتس اپ و …. با لگ همراه بود 
راهکاری برای این مشکل وجود نداره؟
ممنون

**Comment by sajadshadmn** [comment]
همان تایم با RTT مشکل لگ و پینگ وجود نداشت
ممنون

**Comment by Azumi67** [comment]
> سلام سپاس از زحمات شما روی حالت پنج با دوتا سرور خارج که انجام دادم پینگ خیلی بالا بود در حدی که به جز اینستا واتس اپ و …. با لگ همراه بود راهکاری برای این مشکل وجود نداره؟ ممنون

سلام . من خودم که تست کرده بودم هم با ایپی 4 و هم ایپی 6، سرعت خوبی داخل اینستاگرام و یوتیوب داشتم. اوپیتیمایزر هم نصب کنید . سرور ایران من برای شاتل هست . حالا من دوباره تست میکنم و همینجا به شما خبر میدم. 2 سرور خارج و یک سرور ایران ایپی 4 و ایپی 6

**Comment by sajadshadmn** [comment]
درست میفرمایید 
اما شیراز که بودم خیلی عالی بود اما اومدم شهرستان و اینجا نت ضعیفتره و به مشکل خوردم در صورتیکه Rtt توی شهرستان بدون مشکل تقریبا با همین نت ضعیف جواب میده
اپتیمایزر هم نصب میکنم
ممنون از پاسخگویی و پیگیری شما

**Comment by Azumi67** [comment]
سلام . من روی اینترنت خونه تست کردم. نتایج اینها بود. من تک سرور و ایپی ورژن 6 رو تست کردم. 
![chisel](https://github.com/Azumi67/Chisel_multipleServers/assets/119934376/d93c4dd8-dd00-4081-95e8-082c92f5afcf)
و اسپید تست که روی نت خونه هست و برای گیم محدودش کردم.
![shatel](https://github.com/Azumi67/Chisel_multipleServers/assets/119934376/3e2906ec-c904-4035-adb8-09613e3ded27)
داخل یوتیوب اینها هم مشکلی نبود. اینستاگرام رو نگاه نکردم. تانل ها مختلف رو تست کنید. اونی که برای شما خوبه رو پیاده سازی کنید.
