### ISSUE TITLE
احتمالا باگ

### ISSUE THREAD

**Issue by KanekiDevPro** [Azumi67/Chisel_multipleServers#10]
سلام وقت بخیر تانل 1 ایران و 5 خارج جواب میده فقط رو یه سرور خارج و بقیه سرور ها رو ادد کردنی پینگ نمیده از چی میتونه باشه چند بار هم ریبیلد کردم و ایپی تمیزه و فایروال باز

**Comment by KanekiDevPro** [comment]
البته اوبنتو اون دوتا 20 بود و جدید ها که میخوام اضافه کنم 22 ربطی داره یا نه ؟

**Comment by Azumi67** [comment]
سلام. من تغییر temporary dns رو برای اینکه بعضی ها مشکل داشتند برداشتم. شما حتما اطمینان پیدا کنید که chisel بر روی سرورتون نصب شده. حتما dns هاتون رو تغییر بدید. در صورت مشکل service status را از داخل /etc/systemd/system
نگاه کنید و ببینید چه خطاهایی داده.

**Comment by KanekiDevPro** [comment]
چک میکنم خبر میدم بهتون پس ربطی به اوبنتو نسخه های متفاوت نداره ؟
