### ISSUE TITLE
multi port v6 tunnel

### ISSUE THREAD

**Issue by mohsenabedi-dev** [Azumi67/Chisel_multipleServers#11]
ممنون میشم تانل روی مولتی پورت رو هم اضافه کنید

**Comment by Azumi67** [comment]
سلام میشه چنین چیزی اضافه کرد اما نمیدونم ایا تانل کشش رو داره یا خیر. مثلا 50 تا پورت

**Comment by mohsenabedi-dev** [comment]
مشکلی که من دارم روی پنل کافکا هست
من روی این پنل تا الان به صورت مولتی پورت کار کردم و برای هر یوزر یه پورت ایجاد شده
تا الانم این پنل با روش پنل به پنل اوتباند تانل شده بود روی v4
اما الان با فشار بالای فیلترینگ  باید تانل v6 استفاده کنم که اونم برای این 500 تا پورت باز خیلی سخته
شما چه راهی پیشنهاد میدید!؟

**Comment by Azumi67** [comment]
همون تانل پنل به پنل اما با ایپی ورژن شش رو ادامه بدین چون خیلی پورت هاتون زیاده.

**Comment by mohkhz2001** [comment]
خیلی عالی میشه اگر مولتی به صورت دل بخواهی کنید یا خودش به صورت اتوماتیک از روی پورت های فعال سیستم که مربوط به x-ui هستند تشخیص بده و لیست رو نمایش بده

**Comment by mohsenabedi-dev** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/tree/master 
این روش هست برای مولتی پورت ولی اختلال داره

**Comment by mohsenabedi-dev** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/tree/master
این روش هست برای مولتی پورت ولی اختلال داره

**Comment by mohkhz2001** [comment]
@mohsenabedi-dev من دارم استفاده میکنم اوکیه

**Comment by mohsenabedi-dev** [comment]
> @mohsenabedi-dev من دارم استفاده میکنم اوکیه
یه مشکلی که دارم چون کانکشنم خیلی بالا هست بحث ریستارت کردن این تانل هست
یکی دیگه از مشکلات سر اینستاگرام هست
ممنون میشم id تلگرامتون رو بدید بتونم ازتون کمک بگیرم
