### ISSUE TITLE
دانلود و آپلود واتساپ

### ISSUE THREAD

**Issue by saedgholami** [Azumi67/Chisel_multipleServers#12]
سلام و عرض ادب
کانفیگ هایی که با تک سرور tcp ایجاد شدن با واتساپ عکس و فیلم نه دانلود میشه نه ارسال میشه. تلگرام و اینستاگرام چنین مشکلی نداره. راه حل چیه
با تشکر

**Comment by Azumi67** [comment]
سلام . اگر از پنل استفاده میکنید، ترافیک اونها رو از وارپ وایرگارد رد کنید. داخل اینترنت باید اموزشش باشه. احتمالا مشکل شما حل بشه

**Comment by saedgholami** [comment]
روی همین سرور دکودمودور ران کردم کانفیگ های دکو واتساپ مشکلی نداره

**Comment by saedgholami** [comment]
> سلام . اگر از پنل استفاده میکنید، ترافیک اونها رو از وارپ وایرگارد رد کنید. داخل اینترنت باید اموزشش باشه. احتمالا مشکل شما حل بشه 

کل ترافیک از وارپ عبور دادم ولی مشکل همچنان پابرجاست

**Comment by Azumi67** [comment]
> > سلام . اگر از پنل استفاده میکنید، ترافیک اونها رو از وارپ وایرگارد رد کنید. داخل اینترنت باید اموزشش باشه. احتمالا مشکل شما حل بشه
> 
> کل ترافیک از وارپ عبور دادم ولی مشکل همچنان پابرجاست

دلیل های زیادی میتونه داشته باشه . من خودم شخصا مشکلی ندارم . ببینید کل ترافیک رو نگفتم. فقط مثلا geosite meta از وارپ وایرگارد که افت سرعت هم نده . اگر هدر میزنید نزنید یا برعکس. کانفیگ های مختلف تست کنید. اگر ایپی 4 هست ، ایپی 6 رو تست کنید. optimizer تست کنید. همه اینکار هارو بکنید و ببینید چی میشه.

**Comment by hhamed1989** [comment]
> سلام و عرض ادب کانفیگ هایی که با تک سرور tcp ایجاد شدن با واتساپ عکس و فیلم نه دانلود میشه نه ارسال میشه. تلگرام و اینستاگرام چنین مشکلی نداره. راه حل چیه با تشکر

توی ایرانسل این مشکل هست وقتی از هدر استفاده نکنید.
راه کار استفاده از WS بجای TCP
یا استفاده از TCP+Header
