### ISSUE TITLE
استفاده ازپروتکل udp  ipv6

### ISSUE THREAD

**Issue by apcac** [Azumi67/Chisel_multipleServers#13]
پروتکل udp روی نت همراه اول با open vpn تانل نمیشه میشه برطرف کرد ؟

**Comment by Azumi67** [comment]
شما یا سرور ایرانتون بر روی ان اپراتور محدود شده هست یا سرور ایرانتون اون تانلی رو که میزنید را باهاش اختلال دارد. میتوانید تانل های دیگه هم تست کنید و ببینید ایا نتیجه متفاوت است یا خیر.
