### ISSUE TITLE
ارور 403 گوگل با روش tc ipv6

### ISSUE THREAD

**Issue by TsTeam2** [Azumi67/Chisel_multipleServers#14]
سلام
من مثل ویدیویی که تو یوتیوب بود با ipv6 tcp تانل زدم همون گزینه 3 ولی ارور 403 میده وقتی تو گوگل چیزی میزنم!
راه حلی داره؟

**Comment by Azumi67** [comment]
باید ترافیک گوگل را از ایپی 4 رد کنید. از داخل پنل خودتون فکر کنم امکان پذیر باشه. در موردش تحقیقات کنید.
