### ISSUE TITLE
تانل 5 سرور ایران 1 سرور خارج

### ISSUE THREAD

**Issue by AliHemmati79** [Azumi67/Chisel_multipleServers#15]
سلام وقت بخیر
تو روش ۵سرور ایران و ۱ سرور خارج 
اگه از دوتا سرور ایران استفاده کنیم
و پورت اینباند یکسان بدیم
مثلا اگه ۱ گیگ استفاده بشه از هر سرور ۱ گیگ کم میشه یا این ۱ گیگ بین دو سرور تقسیم میشه؟

**Comment by Azumi67** [comment]
سلام. بستگی به این داره که یوزر شما یا خودتون از کدوم سرور بیشتر مصرف کنن. اگر از سرور دو بیشتر مصرف شده ، مصرف سرور دو بیشتر خواهد بود.  از هر سرور یک گیگ کم نباید بشه.
