### ISSUE TITLE
Reboot Server iran

### ISSUE THREAD

**Issue by hosseinchicago** [Azumi67/Chisel_multipleServers#16]
سلام
رو اسکریپت تغییر جدیدی دادید ؟ تو سرور ایران ، اگر سرور رو ریبوت کنیم تنظیمات ریست میشه و مجدد باید از اول تنظیم کرد ، درصورتی که قبلا اینطور نبود

**Comment by Azumi67** [comment]
سلام. نه تغییرات خاصی نبوده. قمستی که تست کردید و این مشکل بوده رو هم بگید.

**Comment by hosseinchicago** [comment]
سرور ایران رو بعد از کانفیگ و ست کردن ip خود سرور ایران ، و‌برقراری ارتباط ، هنگامی که سرور رو Reboot میکنم ، پس از اجرای مجدد سیستم عمل سرور ایران ، ارتباط برقرار نمیشه ، من مجدد سرور ایران را کانفیگ کردم تا ارتباط درست بشه ( منظور از کانفیک اجرای اسکریپت سر کار عالی هست)

**Comment by hosseinchicago** [comment]
من الان نزدیک به دو‌ماه است که این روش رو استفاده میکنم ، روزی یکبار هم سرورها رو ریبوت می کنم ، این مورد تازه اتفاق افتاده

**Comment by Azumi67** [comment]
متوجه ام. منظور من این بود کدوم گزینه رو میگید که کد هاش رو نگاه کنم و خودمم تست کنم

**Comment by hosseinchicago** [comment]
اهان همون گزینه ۱ اسکریپت ، کانفیگ سرور ایران

**Comment by hosseinchicago** [comment]
گزینه سرور ایران

**Comment by hosseinchicago** [comment]
اگر تغییری نداشته شاید از سرور من اشکال هست و من Rebuild میکنمش

**Comment by Azumi67** [comment]
کد ها رو نگاه کردم و روی دو سرور تست کردم و مشکلی نبود. بعدا تست کنید و ببینید باز هم مشکل دارید یا خیر.
