### ISSUE TITLE
بیش از ۵ سرور

### ISSUE THREAD

**Issue by LonUp** [Azumi67/Chisel_multipleServers#17]
من ۲ عدد سرور داخل و ۱۴ عدد سرور خارج دارم .  هر سرور خارج به حداقل یکی از سرور های داخل تانل خواهد شد . باید تک سرور و دونه دونه انجام بدم همشو  روی پورت های مختلف ؟

**Comment by Azumi67** [comment]
شما در صورت داشتن منابع کافی میتونید 7 سرور خارج رو به یک سرور ایران تانل کنید. برای دو سرور خارج دیگر میتوانید از همان سرور 5 خارج استفاده کنید یا میشود تعداد سرور خارج بیشتری را به این اسکریپت اضافه کرد اما نمیدونم ایا کشش را دارد یا نه .

**Comment by LonUp** [comment]
چطور ۷ سرور رو به یک سرور ایران اضافه کنم ؟ نهایت ۵ تا در منوی اسکریپت نوشته. و اگه دستی بخوام تعداد بیشتری خارج اضافه کنم چطور انجامش بدم خودم دستی دونه دونه انجام بدم این تانلینگ رو . حقیقتا سرعت چیزل عالیه اما برای استفاده بیش از ۵ خارج یا بیش از ۵ سرور داخل چالش هایی داره .  اگه راهنمایی کنید چطور انجام بدم به صورت دستی ممنون میشم .  خودم از طریق ۱ سرور ایران و ۱ سرور خارج خواستم انجام بدم اما وقتی اولی رو تانل میکنمو بعدش دومی رو تانل میکنم روی پورت متفاوت ... اولی قط میشه. چطور اسکریپت رو توی چند تا پوشه مختلف ذخیره کنم تا بتونم توی هر پوشه به صورت جدا یه تانل جدا رو انجام بدم . اینطور فکر میکنم بشه هر تعداد که خواستیم اوکی کنیم.

**Comment by Azumi67** [comment]
سلام. بذارید شب دو تا دیگه به سرور های خارج اضافه میکنم.

**Comment by Azumi67** [comment]
اپدیت شد بررسی کنید. وقت برای تست کردن نداشتم. همینجا اطلاع بدید.

**Comment by LonUp** [comment]
ممنون از پیگیری . من نیم ساعت دیگه برم پای سیستم تست میکنم . بازم ممنون

**Comment by LonUp** [comment]
تست کردم . نشد .  من ۷ تا خارجو اوکی کردم ایرانم اوکی کردم  ولی تایم اوت میده روی تمامی ۷ تا

**Comment by Azumi67** [comment]
یعنی قبلا اوکی کرده بودید ؟ چون چیز خاصی در کد تغییر نکرده . فقط دو تا سرور خارج اضافه شده.

**Comment by LonUp** [comment]
فکر میکنم که یه مشکلی وجود داره .  چون قبلش من دوتایی هم اوکی کرده بودم الان این ۷ تایی نشد... تکی رو تست کردم تکی هم نمیشه .روی سرور ایرانم . توی این ۷ تایی احتمالا چیزی اشتباه زدم که تکیم الان اوکی نمیشه . از اول باید برسی کنم . ممنون از پیگیری

**Comment by LonUp** [comment]
اوکیه . تست کردم . ایپی ایران رو داشتم اشتباه میزدم  حله کاملا

**Comment by Azumi67** [comment]
مرسی که اطلاع دادین
