### ISSUE TITLE
قطعی چند دقیقه ای

### ISSUE THREAD

**Issue by saedgholami** [Azumi67/Chisel_multipleServers#19]
سلام
ارتباط تانل از طریق تک سرور tcp برقرار کردم در طول شبانه روز بالغ بر 20 بار قطعی در حد 10 دقیقه ای رخ میده . vless tcp with header 
مشکل از کجا میتونه باشه؟

**Comment by Azumi67** [comment]
سلام. سرور ایرانتون رو بررسی کنید که اختلال نداشته باشه . کانکشن بدون Header و با وارپ وایرگارد تست کنید. لاگ های سرویس و تانل رو بررسی کنید با دستوراتی که داخل گیت هاب گذاشتم. اینطوری شاید مشکلتون رو متوجه بشید . optimizer هم نصب کنید.
