### ISSUE TITLE
آیا راهی برای مولتی پورت هست؟

### ISSUE THREAD

**Issue by hatinati2** [Azumi67/Chisel_multipleServers#2]
سلام وقت بخیر
با تشکر از زحمات شما 
بیش از 150 پورت پنل درگیر هست
آیا راهی هست که اسکریپت برای مولتی پورت هم بشود استفاده کرد؟
مرسی

**Comment by Azumi67** [comment]
سلام .مرسی . برای اون روش بهتره از تانل اقای رادکسوت یا همون پنل به پنل استفاده کنید.
