### ISSUE TITLE
ناپایداری 

### ISSUE THREAD

**Issue by 2EXEN** [Azumi67/Chisel_multipleServers#21]
سورس برای یه ساعت مشخصی پایداره و همه چی اوکیه حتی با یوزر بالا اما یکدفه وارد حالت نوسان میشه که طبق برسی من یا مشکل از اوت باند روی سرور خارجه یا بخش اتو ریستارت یه باگی داره فرصت نکردم دقیق برسی کنم

**Comment by Azumi67** [comment]
ریستارت که باید انجام بشه. شما نخست بررسی کنید و ببینید سرویس شما بر اساس time interval ای که قرار دادید ریست میشه یا خیر.
 crontab -e
و بررسی تایم ریست در 
systemctl status servicename

**Comment by 2EXEN** [comment]
همه این کار هارو انجام دادم از قبل دقیقا سر تایم ریست دیفالت که عددش برای من 6 بود شروع میکنه قاطی کردن , به عبارتی 3 دقیقه اوکیه بعد 1 دقیقه قطع میشه و دوباره همین لوپ تا زمانی که برم دستی سورس رو ریست بدم و مشکل حل میشه

**Comment by 2EXEN** [comment]
و مشکل مشابه سورس RTT اینجا بازم وجود داره مقدار اوت باند سرور خارج از عدد 1024 رد میشه سورس ناپایدار میشه

**Comment by Azumi67** [comment]
کسی از دوستان که بررسی کردن هم میگن پایین بودن هسته cpu میتونه باعث قطعی تانل شما شود اما خب من وقت تست کردن نداشتم. همچنین میتوانید با دستور tail /var/log/syslog ببینید که cron عمل کرده یا خیر. از خود لاگ تانل و سرویس هم میشود نگاه کرد. journalctl

**Comment by 2EXEN** [comment]
من با حداکثر قدرت سرور دارم ماجرا رو تست میکنم سرور 16 هسته ای گذاشتم برای ماجرا استفاده خوبی از منابع و سی پی یو داره شک دارم مشکل از سمت منابع باشه من مشکلی که دیدم از سمت اوت باند بود که روی چندین تانل ریورس دیگه هم همین مشکل وجود داشت حالا باز من برسی میکنم و نتیجه رو توی همین بخش ارائه میدم

**Comment by 2EXEN** [comment]
با سرور منابع بالاتر هم حتی تست کردم هر دو طرف هم ایران هم خارج با منابع 16 هسته ای تست کردم مشکل از سمت سورس خارج ایجاد میشه توی لاگ سرور ایران همه چی اوکیه و بدون مشکل ولی سمت سرور خارج بعد از زمان مشخصی که اوت باند های سرور خارج از 1024 رد میشه شروع میکنه قاطی کردن و ناپایدار شدن و اگر تعداد ریکوئست از حدی بالاتر بره کلا سرویس از دسترس خارج میشه
