### ISSUE TITLE
مشکلات پایداری

### ISSUE THREAD

**Issue by 2EXEN** [Azumi67/Chisel_multipleServers#23]
در 2 هفته اخیر که در حال استفاده از این تانل بودم متوجه مشکلی در عملکرد cron شدم .

**Comment by Azumi67** [comment]
اپدیت جدید رو تست کردید که ریست تایمر 30 دقیقه با دستور کیل اضافه شده ؟ و میتونید کرون رو با دستور tail بررسی کنید که ببینید انجام میشه یا خیر. 
ریست تایمر هم که میشه از طریق edit menu یا خودتون ب صورت manual تغییر بدید

**Comment by 2EXEN** [comment]
به صورت دقیق ماجرا رو برسی کردم و وقتی دیدم سورس میخواد بر اساس ریست تایمری که براش ست شده ریست بده شروع میکنه به قاطی کردن , قبلا در این باره issue باز کرده بودم که نتیجه ای نداد
در بارزه های زمانی متفاوت برسی کردم تانل واکنش های متفاوتی میده
ظهر ها نسبتا پایداره و اخر شب ها از ساعت 11 همه چی بهم میریزه (بحث دیتا سنتر و موارد دیگه هم چک کردم که اختلالی نباشه)

**Comment by 2EXEN** [comment]
البته اپدیت جدید رو هنوز تست نکردم نتیجه اپدیت رو توی همین بخش میگم

**Comment by 2EXEN** [comment]
تقریبا بعد از 3 روز تست ماجرا , هنوز درگیری روی اتصال هستش و عمده مشکل روی کانفیگ خارج هستش , تغییرات اخیر به نسبت توی کنترل کردن استفاده بهینه از پهنای باند بهتر شده اما هنوز درگیری هایی روی عملکرد cron وجود داره , عملکرد kill باعث یسری تداخل میشه توی لاگ مشاهده شده , cron هم وقتی میخواد اجرا بشه در حین اجرا باگ میخوره البته این ماجرا توی تعداد کانکشن بالا باگ میخوره و نمیتونه درست ریست بده توی کانکشن های پایین مشکلی ندیدم من

**Comment by 2EXEN** [comment]
به طور کلی سورس ریوس توی هر مدلی که دیدم توی بخش سرور خارج به مشکل میخورن و نمیتونن اوت باند رو به  درستی کنترل کنن اما سورس شما با جدا کردن کانفیگ ها تا حدی مشکل رو حل کرده و به نسبت به بقیه ریورس های موجود پایدار تره و در حالت کلی همه سورس های ریورس با تعداد کانکشن های خیلی کم اصلا مشکلی ندارن وقتی تعداد کانکشن زیاد میشه شروع به تداخل میکنن که سورس شما هم تقریبا همینطوره

**Comment by Azumi67** [comment]
مرسی به خاطر فیدبک . بررسی کردید که چه لاگی در موقع اختلال پس از Kill کردن گرفتید ؟ میدونم که کرون به درستی کار میکنه اما میتونه شاید در سرور های بیشتر و کانکشن های بیشتر، پروسه ای باعث به درستی اجرا نشدنش بشه . ایا تلاش کردید برای هر سرور خارج، دقیقه ای متفاوتی را بذارید. مثلا با 1 min delay . 
اگر بتونید لاگ ها را برای من هم بفرستید که مطالعه کنم خوب میشه ولی در حالت کلی چنین مشکلی روی تعداد کانکشن بالا بر روی ریورس ها به وجود میاد که باید کانشکن ها تفکیک سازی بشه و البته optimizer هم فکر میکنم کمکی میکنه . 
تو فکرش هستم که بتونم بهترش کنم .

**Comment by 2EXEN** [comment]
من از ترکیب 3 سرور ایران و یک سرور خارج استفاده میکنم و کل این تاپیک بر اساس اون روشه وقت نکردم لاگ رو سیو کنم و نگه دارم تا اخر شب براتون لاگ رو همینجا میزارم که چک کنید , و نکته دیگه اینه که مشکل زمانی ایجاد میشه که پیک مصرف اینترنت باشه که میشه حدود 9 شب تا 1

**Comment by Azumi67** [comment]
یک موردی یادم اومد بهتون بگم . داخل آپدیت جدید برای هر سرور ایران که اضافه میشه باید پورت جداگانه انتخاب بشه . اگر این کار رو نکردید ، این مورد رو لحاظ کنید .

**Comment by 2EXEN** [comment]
بله اپدیت اخیر مهم ترین تغییرش همین مسئله بود که تاثیر زیادی توی پایداری ماجرا داشت اما باز سورس گاه گاهی گیج میزنه ( کانکشن بالا ) .
از 2 روز پیش منتظرم ماجرا باگ بخوره که هنوز اتفاقی نیوفتاده که بتونم لاگ رو ارسال کنم 
کمی تغییرات در nice دادم بنظر کمی پایدار شده
