### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by LonUp** [Azumi67/Chisel_multipleServers#24]
من بدون مشکل از تانل استفاده میکردم .  اما خواستم کشور تانل رو عوض کنم برای همین استاپ کردم و خواستم دوباره تانل ران کنم . هیچ جوره ارتباط برقرار نمیشه . ۳ تا سرور ایران مختف و ۳ تا خارج مختلف رو تست کردم روی تانل ۱ به ۱  و نشد .

**Comment by Azumi67** [comment]
لطفا لاگ هاتون رو با اون دستوراتی که داخل گیت هاب قرار دادم، اینجا بفرستید . اینطوری میتونید مشکلش رو بفهمید. باگ فکر نکنم باشه چون خیلی تست شده.

**Comment by LonUp** [comment]
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/533624da-f011-4776-b3c1-0f640519598f)
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/07423a56-146b-42ca-a168-dbd4e7f66e15)
موقع انجام مراحل همچیز اوکیه . روی دوتا سرور دیگه تست کردم شد. ولی دوتا ایران دارم روی اونا این مشکله. و با چند تا خارجم تست کردم . ریورس تانل عادی شد روش.. ولی چیزل نشد . این شاتای بالا هم مربوط به وضعیت تانل در هر دو سروره

**Comment by Azumi67** [comment]
سرویس ایران اصلا فعال نیست . لطفا با دستور 

journalctl -u نام.service

بررسی کنید که چرا داخل سرور ایران ، تانل برقرار نشده ‌ احتمالا نتوانسته چیزل رو دانلود کنه

**Comment by LonUp** [comment]
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/4322e86d-3b9a-43ad-9e54-09bc3ab57cbc)
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/58514780-be0a-491d-98cc-5b46d917a2af)

چطور حلش کنم ؟ ممنون ازتون که راهنمایی میکنید

**Comment by LonUp** [comment]
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/1b63bf46-8dab-4bea-ac2d-4835e501b193)

موقع اجرا روی ایران بدون مشکل اجرا میشه ولی

**Comment by Azumi67** [comment]
نتوانسته آدرس ایران رو assign کنه. معمولا یا به خاطر اینه که آی‌پی آدرس رو اشتباه میدید یا به خاطر اینه که نصب نیست. داخل مسیر روت ، ls بگیرید و ببینید چیزل هست یا نه .کامل با دستور rm -rf chisel پاکش کنید . سپس یک DNS temporary در داخل nano /etc/resolv.conf قرار بدید 
به طور مثال nameserver 1.1.1.1 و دوباره تلاش کنید و چیزل‌ رو نصب کنید.

**Comment by LonUp** [comment]
با اسکریپت https://github.com/hawshemi/Linux-Optimizer تغییراتو انجام دادم
چیزل رو با rm -rf chisel از روت دلیت کردم 
و دوباره دستور نصب رو اجرا کردم(دستور اولی)
این وضعیت دی ان اس ها:
![7135](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/f871e5e6-7d9f-49f4-9ca3-9d8be5236368)
وضعیت ست کردن تک سرور ایپی ۴ روی ایران(جاهایی که هایلایت کردم و زیرش خط کشیدم .. نمیتونه کمک کنه به حل مشکل؟ بنظر اونجا مشکلی هست)
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/85017d47-c647-433d-a6ab-6a1fa7200857)

وضعیت تانل با دستور اول لاگ در سرور ایران؛
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/532bb0a1-93fe-410e-8bf4-4b31467f9fdf)

وضعیت تانل با دستور دوم لاگ در سرور ایران:
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/839b7454-13c7-4c79-8c2a-0636f7f04edd)

وقتی که تازه به سرور لاگین میشم . ایپی سرورو نمیاره توی همون صفحه اصلی . ممکنه کمکی به حل مشکل بکنه ؟
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/51d243fb-cc0a-4c98-8e20-1d92dce560c6)

ایپی سرور ایران هم درست وارد میکنم .  و اوکیه .. دقیقا ایپی که بهش اس اس اچ میزنم برای ورود به سرور رو وارد میکنم
اگه میتونه سرورم کمکی به مشکل بکنه راه ارتباطی بگید تا اطلاعات ورود ssh رو در اختیارتون قرار بدم

**Comment by Azumi67** [comment]
ببینید مشکل از اون خطای هایلایت شده نیست . اون برای اینه که دستور دقیقه و ساعت رو پاک کنه. مشکل اونجایی هست که نوشته can't assign IP address که معمولا به دلیل اینه که آی‌پی آدرس سرور دیگری به جز سرور اصلی داده شده است. میتونید سرورتون رو به ایمیلی‌ که در‌ گیت هاب فرستادم بفرستید .

**Comment by LonUp** [comment]
براتون فرستادم . اگ نیازه سرور خارجم بدم . بگید بهم برای تست کردن و... ممنون
