### ISSUE TITLE
باگ مولتی سرور

### ISSUE THREAD

**Issue by sawman17** [Azumi67/Chisel_multipleServers#25]
سلام ازومی جان خسته نباشی
ببین چیزل و اف ار پی جفتشون روی تک سرور عالین 

ولی جفتشون روی مولتی سرور باگ دارن 
حالا نمیدونم مشکل از منه یا باگیه که هست 

من 2 تا سرور خارجو به یه سرور ایران تانل کردم 
دوتا مشکل میخورم یکی اینکه دقیقا سر ریست تایم ها در سرور خارج 
یکی از سرور رندوم براش مشکل کانکشن کانفیوز پیش میمد که اختلال رو پورته 
پورتمو عوض کردم یه چیز ناشناخته گذاشتم بازم همین مشکل بود و خب نمیدونم باید چه جوری این قضیه رو حل کنم 
چون اگه حل نشه عملا من همیشه باید انلاین باشم و هروقت قطع شد سرور خارجو ریبوت کنم تا درست شه

بعد اومدم گفتم اقا اصن بیخیال ریست نمیخوام 
تایشمو گذاشتم رو ده ساعت و یکی از سرور های خارجم که میخواسم کانکت شه توی لاگ میدیدم زده EOF و وصل نمیشه و باز ریبوت کردم تا درست شد 

ممنون میشم اگه راه حلی داری بهم بگی 
یا اگه جاییو اشتباه میکنم بازم راهنماییم کنی 
مرسی بابت کمک ها و اموزش هات

**Comment by Azumi67** [comment]
سلام مرسی. افرادی هستن که هفت سرور هم وصل کردن و استفاده میکنند. شما داخل همه سرور هاتون برید داخل مسیر سرویس ها و ببینید چه سرویس های دارید که در حال اجراست و داره باعث اختلال میشه. اگر frp هست حتما باید شماره v2ray number  رو درست بدید وگرنه باعث اختلال میشه. تنها با خواندن لاگ و بررسی اینکه چه سرویس های فعال دارید میشه متوجه شد که چرا اختلال دارید.

**Comment by sawman17** [comment]
ممنون بررسی میکنم بازم 

یه چیز دیگه اینکه من روی سرور ایرانم هرچی ریست تایم ست میکنم میزنه اینارو نشونم میده و به نظرم ست نمیشه اصلا 
راه حلی برای این هستت؟!
چون هر بار میام ریست تایمو تغییر میدم بهم میگه قبلی اصن وجود نداشته و الان ست شد و همین داستان ادامه داره هی

✨ Deleting Previous Crons..
Cron doesn't exist, moving on..!
✔ Cron entry added successfully!

**Comment by Azumi67** [comment]
اون خطا نیست . اون میاد بر اساس دقیقه و ساعت تمام دستورات کرون رو که اضافه شده رو پاک می‌کنه . وقتی دستور ساعت هست ، دستور دقیقه نیست و برای همین چنین پیامی می‌بینید .شما وقتی کرون رو اضافه کنید،‌ میتونید با دستور crontab -e بررسی کنید که ست میشه . چیز خاصی نداره.

**Comment by sawman17** [comment]
ازومی جان سلام
فک کنم مشکلی که داره با وارپ هست که از طریق اسکریپت خود ایکس یو ای ثنایی داخل سرور نصب میکنیم 

حالا فعلا من چند ساعته وارپو پاک کردم مشکلی نداشتم 
خودت راجب این اطلاعی نداری؟!
یا با وارپ تست نکردی رو مولتی سرور ببینی مشکلی هست یان نه؟!
چون رو تک سرور مشکلی نیست ولی روی مولتی سرور این مشکل هست 
هم روی frp هم چیزل مستقیم و هم چیزل معکوس با مولتی سرور این مشکلو داشتم

حالا تستم کامل تر شد بهت اعلام میکنم حتما 
ولی اگر خودتم اطلاعی داره راجبش حتما بهم بگو 
ممنونم ازت

**Comment by Azumi67** [comment]
سلام . نه خودم این مورد تست نکردم . تست کنید و بهم اطلاع بدید . مرسی.

**Comment by sawman17** [comment]
![photo_2024-02-05_23-37-13](https://github.com/Azumi67/Chisel_multipleServers/assets/158520683/5ff31f17-fab2-4d1a-87d6-b0ffc627d07d)
![photo_2024-02-05_23-37-30](https://github.com/Azumi67/Chisel_multipleServers/assets/158520683/9db8e7ab-d769-45b4-a909-385f32b64958)


سلام ازومی عزیز من سرور خیلی وقتا اینجوری میشه و برای چند دقیقه قطعه کامل و دوباره وصل میشه 
مشکل از کجاست به نظرت؟! و راه حلش چیه؟!

**Comment by Azumi67** [comment]
سلام. خطای broken pipe معمولا به خاطر این دلیل ها هست ، کمبود منابع ؛ تایم اوت یا بسته شدن ارتباط.

**Comment by sawman17** [comment]
سلام ازومی جان 
ببخشید من هرشب پیام میدم ولی یه سرورام خیلی داره اذیت میکنه مجبورم بپرسم 
ممنون که جواب میدی همیشه 
من اخیرا با این مشکل روبرو شدم و باید سرور ایرانو ریبوت کنم تا مشکل حل شه 

میدونی مشکل از کجاست؟!
ممنون میشم راهنماییک کنی
![Uploading photo_2024-02-06_23-05-40.jpg…]()

**Comment by sawman17** [comment]
سلام ازومی جان 
ببخشید من هرشب پیام میدم ولی یه سرورام خیلی داره اذیت میکنه مجبورم بپرسم 
ممنون که جواب میدی همیشه 
من اخیرا با این مشکل روبرو شدم و باید سرور ایرانو ریبوت کنم تا مشکل حل شه 

میدونی مشکل از کجاست؟!
ممنون میشم راهنماییک کنی


![photo_2024-02-06_23-05-40](https://github.com/Azumi67/Chisel_multipleServers/assets/158520683/2a783e59-4e15-4aa3-9ba2-7c315e196aca)

**Comment by Azumi67** [comment]
سلام. ریست تایمرتون چنده ؟ تلاش کردید ببینید با اون دستور Kill هم مشکل حل میشه یا خیر ؟ چون این خطای دریافتی پکت هست که فکر کنم در این زمینه ربطی داره به network connectivity . شما اگر با ریبوت این مشکلتون حل میشه تلاش کنید خودتون دستی دستور 

`/etc/reschisel.sh`

اجرا کنید و اگر فیکسش کرد، ریست تایمر رو بر اساس اختلاتون تنظیم کنید.

**Comment by sawman17** [comment]
ببنید الان روی 30 دقیقس 
کردم روی 15 دقیقه ببینم بهتر میشه یا نه که یهو تبدیل شد به همون ارور broken pipe 
در صورتیکه من رمم 2 بود و 2 گیگ دیگه هم سواپ کردم که این رم کم نیاره یوقت 
از طرفی سی پی یوم یکه که اصن بررسی کردم سی پی هم بالای 50 نرفته که بخواد منابع کم بیاره 

دستوره کیل هم نمیدونم چه جوری بزنم ولی اگر منظورتون همون ادیت ریست تایمر هست که گذاشته بودم روی 30 بعد روی 15 گذاشتم

حالا به نظرتون چه کنم؟!

**Comment by sawman17** [comment]
راسی یه چیز دیگه 
این عکس برای سرور ایران بودا
تو ریورس چیزل توی سرور ایران هم ریست تایمر اد کنم؟!

چون من فقط توی سرور خارج اد کرده بودم(ینی اسکریپتم فقط برای خارج میپرسید)
حالا برای ایران هم اد کنم به نظرتون؟
تایمش با ریست تایم خارج یکی باشه یا متفاوت؟

**Comment by Azumi67** [comment]
هر دو ریست تایم در هر دو سرور باید یکسان باشد. داخل سرور ایران به صورت اتومات روی 30 دقیقه هست. از اونجا مشکلات network connectivity به نظر دارید، در صورت ادامه مشکل بر روی سرور مشکل دار ، Kuma نصب کنید و اپتایم و دان تایم سرورتون رو مشاهده کنید.

**Comment by sawman17** [comment]
جشمم ممنونمم بازم
