### ISSUE TITLE
پورت فوروارد روی ipv6

### ISSUE THREAD

**Issue by RAfrwrk** [Azumi67/Chisel_multipleServers#26]
سلام
اگر میشه لطف کنین پورت فوروارد رو روی ipv6 هم اضافه کنید. با دادن ipv6 اضافی روی سرور ایران مثل ipv4 دیتا به سمت سرور خارج روت بشه.
ممنون

**Comment by Azumi67** [comment]
سلام. من کمی درگیر هستم و دارم روی چند روش دیگه کار میکنم. دقیق بگید منظورتون چیه ؟

**Comment by RAfrwrk** [comment]
سلام در سمت سرور ایران ipv6 رو هم برای پورت فوروارد اضافه کنید که اگه کسی ipv6 اضافه داشت بتونه از روتینگ اون هم استفاده کنه به سمت سرور خارج. وهمچنین قابلیت flow control  رو هم اگه وقت داشتین برای Tcp اضافه کنین ممنون.
config 1 ipv4 Address: port
config 1 ipv6 Address: port
این هم باشه
![1](https://github.com/Azumi67/Chisel_multipleServers/assets/157138592/bbb759b8-2361-4177-b2c6-68fb86b72e4f)

**Comment by Azumi67** [comment]
سلام. اون ایپی 4 به منظور نمایش ایپی در اخر اسکریپت و برای راحتی کار شما میباشد. برای فوروارد نمیباشد
