### ISSUE TITLE
استعلام

### ISSUE THREAD

**Issue by hosseinchicago** [Azumi67/Chisel_multipleServers#27]
سلام خانم مهندس
مزایای چیزل با ip private  و Revers chisel نسبت به هم چی هست ، آیا تو سرعت و امنیت تفاوت دارند یا فرقی ندارد دو روش متفاوت هست؟

**Comment by Azumi67** [comment]
سلام. سرعت که روی هر سرور ایران من دیدم یک چیزی خوبه . من الان خودم تانل gen و ریورس استفاده میکنم و پینگک هم 86 اینها هست. راضی ام اما مصرف بالا میره . پرایوت ایپی هم که یک مقاله هست میتونن ایپی اصلی رو به صورت غیر مستقیم ببینن و برای همین باید روش های جدید تر هم کار کرد . امنیت چیزل هم که خوبه و جز یکی از بهترین تانل ها هست. حالا من از keygen برای امنیت استفاده میکنم اما fingerprint هم میشه استفاده کرد . ریورس هم برای اینه که سرور خارج فیلتره بتونیم از اون سرور استفاده کنیم . مصرفش بالاتره . مستقیم هم که با روش های تانل 6to4 و ترکیبی یا با native ipv6 جواب میده. سرعتشم اوکیه . امنیتشم که با keygen و اینها برقرار میشه .

**Comment by hosseinchicago** [comment]
من مشکلم با ریورس چزل همین مصرف ترافیک رو سرور ایران هست اما سرعت هیچ مشکلی ندارم چون سرورهای خوب میگیرم ، حیف شد اگر پرایوت ، Ip سرور اصلی لو نمیرفت عالی بود
