### ISSUE TITLE
مشکل کندی در بعضی از روز ها در ساعت 11 تا 2 شب

### ISSUE THREAD

**Issue by alexfurd1378** [Azumi67/Chisel_multipleServers#29]
سازنده عزیز میخواستم بدونم علت اینکه در بعضی از روز ها بین ساعت 11 شب تا 2 شب این کندی پیش میاد چیه، یعنی کانفیگ دیر پینگ پاسخگویی میده
کانفیگ با TLS هست با sni مختلف هم تست کردم اما فرقی نکرد و بعد از تقریبا این تایم دوباره اوکی میشه

**Comment by Azumi67** [comment]
سلام این که ساعت خاصی مشکل دارید ، ممکنه به اختلالات سرور ایران با خارج باشه . برای بعضی از سرور ها این اختلال ها به وجود میاد .
