### ISSUE TITLE
رو سه تا سرور تست کردم موقع نصب این ارورو میده

### ISSUE THREAD

**Issue by MosiFantastic** [Azumi67/Chisel_multipleServers#3]
Traceback (most recent call last):
  File "/dev/fd/63", line 2886, in <module>
  File "/dev/fd/63", line 130, in main_menu
  File "/dev/fd/63", line 126, in display_logo
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 28-59: ordinal not in range(256)
لطفا راهنمایی کنید

**Comment by Azumi67** [comment]
سلام. سیستم عامل هاتون چیه ؟ تلاش کنید سیستم عامل های به روز استفاده کنید. اگر بر روی دبیان هستید و مشکل نصب دارید اول دستور زیر را اجرا کنید و سپس دستور اصلی 

sudo apt-get install python-pip -y  &&  apt-get install python3 -y && alias python=python3 && python -m pip install colorama && python -m pip install netifaces

داخل پایتون 2 فکر کنم این مشکل بود. بعضی ها با تغییر سیستم و استفاده ار سیستم عامل جدید به مشکل بر نخوردن. اون دستور بالا هم یک بار اجرا کنید و سپس دستور اصلی ببینید چی میشه

**Comment by MosiFantastic** [comment]
E: Package 'python-pip' has no installation candidate
این ارورو میده من از ابونتو 20 استفاده میکنم

**Comment by Azumi67** [comment]
باید خودم دسترسی به سرور داشته باشم تا ببینم مشکل چیه. بهترین کار برای شما اینه که با اوبونتو 22 هم تست کنید و نتیجه رو بهم بگید
اینم یک تست کنید 
python3 install colorama

**Comment by Azumi67** [comment]
سلام. لطفا این هم تست کنید 

``
sudo apt-get install python3 -y && apt-get install wget -y && apt-get install python3-pip -y && pip3 install colorama && pip3 install netifaces && apt-get install curl -y && python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/Chisel_nologo)
``

**Comment by MosiFantastic** [comment]
بازم همون ارور و میده 


root@srv1702220890:~# sudo apt-get install python3 -y && apt-get install wget -y && apt-get install python3-pip -y && pip3 install colorama && pip3 install netifaces && apt-get install curl -y && python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/Chisel_nologo)
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.20.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: colorama in /usr/local/lib/python3.8/dist-packages (0.4.6)
Requirement already satisfied: netifaces in /usr/lib/python3/dist-packages (0.10.4)
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.68.0-1ubuntu2.21).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "/dev/fd/63", line 2867, in <module>
  File "/dev/fd/63", line 111, in main_menu
  File "/dev/fd/63", line 107, in display_logo
  File "/usr/local/lib/python3.8/dist-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.8/dist-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)
root@srv1702220890:~#

**Comment by Azumi67** [comment]
سلام. ببخشید امکانش هست اینم تست کنید. 
``
sudo apt-get install wget -y && sudo wget -O /etc/logo.sh https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/logo.sh && sudo chmod +x /etc/logo.sh && python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/Chisel_2.py)
``

**Comment by MosiFantastic** [comment]
خیلی ممنون این شد مرسی از همه زحماتتون

**Comment by MosiFantastic** [comment]
البته تو سرور خارجم نصفه میاد نگا کنید


root@srv1702220890:~# sudo apt-get install wget -y && sudo wget -O /etc/logo.sh https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/logo.sh && sudo chmod +x /etc/logo.sh && python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/Chisel_2.py)
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.20.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2023-12-23 15:13:51--  https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/logo.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4626 (4.5K) [text/plain]
Saving to: '/etc/logo.sh'

/etc/logo.sh                              100%[===================================================================================>]   4.52K  --.-KB/s    in 0s

2023-12-23 15:13:51 (24.8 MB/s) - '/etc/logo.sh' saved [4626/4626]


                  ⣾⣿⣿⣿⣿⣿⣿⣿⣿⣯⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⣿⣿
                ⢺⣽⡿⣅⠹⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢿⣿⡻⣿⣻⣿⣿⣿⣁⣴⢟⡻⠻⣯⣌⣿
          ⠔⢫⠆⣾⡿⢷⣮⣥⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠯⠝⠛⠉⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠻⣏⣀⣙⡄⢿⣿⣿⣿⣿⣿⣿⣿⢟
       ⢀⠳⢒⣷⣿⣿⢱⡂⠜⣿⣿⣿⣿⣿⣿⣿⡿⢛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⡿⡱⠟⢀⡇⠸⣶⣿
       ⠈⢩⣣⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⠏⡰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⢻⣿⣭⡽⠟⠫⠅⣿⡿⢶⣿⠿⣻⣿⣿⣿⣿
         ⢠⣿⣿⣿⣿⣿⣉⠻⣿⣿⣿⣿⢏⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢤⠢⣀⣀⠤⢞⢟⣟⣒⣣⠼⡯⡟⢻⡥⡒⠘⣿
        ⢠⠋⣴⡿⡿⣿⡔⠻⣿⣿⣿⣿⣏⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡀⣆⣐⣥⣴⣾⣿⣿⣿⣶⠊⣼⣀⣸⣧⣿⣿⣿⣽
       ⣠⣿⣾⡟⣤⣇⠘⣿⣷⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠄⢻⣿⣿⣿⣿⣿⣿⣽⣻⣿⣿⣿⣿⢿⡍⢻⣿⣿⡇
      ⣰⠏⣾⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⠃⠀⣀⠠⠤⠐⠒⠒⠓⠒⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠐⠒⠒⠒⠤⠤⣀⠀⠘⣿⣿⣿⣿⣿⣿⣷⡟⢰⡿⠻⣟⡚⠻⣷⣿
     ⣰⠃⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠔⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠑⢿⣿⣿⣿⣿⣿⢙⢲⡞⢀⡄⠈⡗⣲⣾⣿⣿⡟⠁
⠀   ⢠⠇⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣀⣀⠀⠀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣾⣿⣷⣯⣼⣿⣿⣿⣿⣿⣿⣿⠀
   ⢀⡎⠀⠀⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⡀⠀⣎⣁⣤⣼⣖⣶⣦⣬⣑⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠖⣈⣭⣤⣴⣮⣭⣴⡦⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣟⠿
⠀  ⡼⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⢧⣤⣾⡿⣿⣿⣿⣿⣯⣽⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  ⣰⣾⢿⣿⣿⣿⣿⣙⣿⣿⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡱⣎⡟⠀
  ⢰⠇⠀⠀⢸⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡠⣾⣿⠟⠀⣿⣿⠛⢽⣿⡿⢿⣿⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠋⠧⣾⣿⡟⠻ ⣿⣿⢿⣿⡟⣿⣿⣿⣿⡿⠿⣿⣿⣿⣿⣿⣿⣿⣾⣾⣿
⠀⠀⣿⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠙⠆⠀⠙⡘⠢⡘⠿⢃⡞⡾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣫⠳⡙⢿⠃⡚⣻⢻⣿⣿⣿⣿⠴⠐⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀
⠀⢸⡇⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⢺⡄⠀⠀⢢⡀⠙⠢⢀⣀⠡⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⠦⣄⣀⣁⠮⠃⣸⣏⣺⣿⣿⠹⡎⣇⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀
⠀⣼⡇⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠣⣷⠀⠀⠉⠙⠛⠦⠲⠒⠂⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠒⠲⠦⠴⠶⠶⠊⣿⠇⣼⣿⣿⡩⢛⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀
⠀⣿⡇⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡘⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⠀⣿⣿⡏⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀Author: github.com/Azumi67
    ______    _______   __      _______         __        _____  ___
   /    " \  |   __ "\ |" \    /"      \       /""\      (\"   \|"  \
  // ____  \ (. |__) :)||  |  |:        |     /    \     |.\   \    |
 /  /    ) :)|:  ____/ |:  |  |_____/   )    /' /\  \    |: \.   \  |
(: (____/ // (|  /     |.  |  //       /    //  __'  \   |.  \    \ |
 \        / /|__/ \   /\  |\  |:  __   \   /   /  \   \  |    \    \|
  \"_____ / (_______) (__\_|_) |__|  \___) (___/    \___) \___|\____\)
+======================================================================+
Traceback (most recent call last):
  File "/dev/fd/63", line 2860, in <module>
  File "/dev/fd/63", line 113, in main_menu
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2551' in position 5: ordinal not in range(256)
root@srv1702220890:~#

**Comment by MosiFantastic** [comment]
مشکل فونت داره انگار

**Comment by Azumi67** [comment]
اگر امکان داره براتون یک سرور که نیازی ندارید و این مشکل رو داره به تلگرام من بفرستید تا ببینم میتونم برطرفش کنم یا خیر
edit : ID removed . Problem Solved.
