### ISSUE TITLE
باگ در مالتی سرور

### ISSUE THREAD

**Issue by LonUp** [Azumi67/Chisel_multipleServers#30]
سلام من ۲ سرور خارج و یک سرور ایران رو میخوام بهم وصل کنم .  سرور اول خارج بدون مشکل وصله . سرور دوم خارج هم سرویس هاش ایجاد شده . و زده کانکتد .. حتی پینگم زده . اما کانفیگای خارج دومی کار نمیکنند
با دستور
sudo lsof -i : 999

روی سرور اول  میتونیم کانکشن هارو ببینیم . اما همین دستور و با پورتی که روی سرور دوم زدم هیچیز نمایش داده نمیشه . فایل هارو هم چکردم همون پورت در سوریس ها در متن فایل وجود داره

**Comment by Azumi67** [comment]
سلام. در سروری که مشکل دارید لطفا لاگ های سرویس رو ببینید . ببینید چه خطاهایی میده . داخل status و journalctl -u

**Comment by LonUp** [comment]
خب من روی سرور مدنظر ۳ تا پورت دارم
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/ecf2abc8-6783-4416-bc02-cfc75420d08d)

که به ترتیب میشه خارج ۱ خارج ۲ خارج ۳
من فقط شماره ۲ رو میفرستم .. برای اینکه زیاد نشه .  مشکل روی هر سه مورد هست اما
ابتدا استاستوس رو در پایین میفرستم که همچیز اوکیه بنظر
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/f0f6ff26-8f9f-426c-98c8-ab056520df6f)

این هم ژورنال 
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/91155537/a832fd24-fc5b-4c7f-bf56-f2b487f625e1)

**Comment by Azumi67** [comment]
خب تانل که کاملا اوکی هست و باگی در کار نیست . شما میتونید از طریق 6to4 و یا native ipv6 هم یک بررسی کنید و ببینید آیا با اون ها این ارتباط برقرار میشه یا خیر. یک بررسی کنید که اگر وارپ وایرگارد فعال کردید ، اون باعث اختلال نشده باشه . بررسی کنید که آیا بدون تانل و به صورت مستقیم هم خود کانفیگتون کار می‌کنه یا نه ( اگر‌سرور فیلتر نیست ). پورت تانل متفاوتی تست کنید . میتونید یک optimizer هم نصب کنید .

**Comment by LonUp** [comment]
مشکل از سمت پنل بود بنظر . و حل شد . ممنون از پیگیریتون
