### ISSUE TITLE
Crontab not apply

### ISSUE THREAD

**Issue by hhamed1989** [Azumi67/Chisel_multipleServers#31]
با سلام
من هرچقدر reset Timer را تغییر میدهم. حتی از داخل crontab ویرایس میکنم یا از داخل crontab حذف میکنم. باز راس 30 ثانیه سرویس ریستارت میشه.
آیا مقدار 30 ثانیه از جای دیگری فراخوانی میشود؟
چرا از منو برنامه ریست تایم اعمال نمی شود و در همه حالات راس 30 ثانیه سرویس ریستارت می شود.

**Comment by Azumi67** [comment]
سلام ریست تایمر که کار میکنه. شما باید بیشتر بررسی کنید که بر روی چه تایمی قرار میدید چون چنین تایمری در اسکریپت وجود ندارد
