### ISSUE TITLE
اختلال

### ISSUE THREAD

**Issue by pouriasharifzad** [Azumi67/Chisel_multipleServers#32]
سلام سرعت و اتصال پایدار نیست و اپتیمایزر شما و هاشمی رو هم روی هر دو سرور نصب کردم لاگ ها رو میزارم اگه فرصت کردین چک کنین ممنون

سرور ایران 

May 06 01:30:02 aa systemd[1]: iran_1.service: Main process exited, code=killed, status=9/KILL
May 06 01:30:02 aa systemd[1]: iran_1.service: Failed with result 'signal'.
May 06 01:30:02 aa systemd[1]: Stopped Chisel Service IRAN.
May 06 01:30:02 aa systemd[1]: Started Chisel Service IRAN.
May 06 01:30:02 aa chisel[132942]: 2024/05/06 01:30:02 server: Reverse tunnelling enabled
May 06 01:30:02 aa chisel[132942]: 2024/05/06 01:30:02 server: Fingerprint TNwfgkAOKB1X4V9kNVR7Va77ik8RYct3Etx4azBsrFM=
May 06 01:30:02 aa chisel[132942]: 2024/05/06 01:30:02 server: Listening on http://[2a04:acc0:18:e:00:00:787c:243b]:443
May 06 01:30:03 aa chisel[132942]: 2024/05/06 01:30:03 server: session#1: tun: proxy#R:26862=>localhost:26862: Listening
May 06 02:00:02 aa chisel[132942]: 2024/05/06 02:00:02 server: session#2: tun: proxy#R:26862=>localhost:26862: Listening
May 06 02:00:03 aa systemd[1]: iran_1.service: Main process exited, code=killed, status=9/KILL
May 06 02:00:03 aa systemd[1]: iran_1.service: Failed with result 'signal'.
May 06 02:00:03 aa systemd[1]: Stopped Chisel Service IRAN.
May 06 02:00:03 aa systemd[1]: Started Chisel Service IRAN.
May 06 02:00:03 aa chisel[149369]: 2024/05/06 02:00:03 server: Reverse tunnelling enabled
May 06 02:00:03 aa chisel[149369]: 2024/05/06 02:00:03 server: Fingerprint TNwfgkAOKB1X4V9kNVR7Va77ik8RYct3Etx4azBsrFM=
May 06 02:00:03 aa chisel[149369]: 2024/05/06 02:00:03 server: Listening on http://[2a04:acc0:18:e:00:00:787c:243b]:443
May 06 02:00:03 aa chisel[149369]: 2024/05/06 02:00:03 server: session#1: tun: proxy#R:26862=>localhost:26862: Listening
May 06 02:23:22 aa chisel[149369]: 2024/05/06 02:23:22 server: session#2: tun: proxy#R:26862=>localhost:26862: Listening
root@aa:/etc/systemd/system#

سرور خارج 

May 05 19:44:07 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 19:44:07 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:07 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:443
May 05 19:44:09 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:09 client: Connected (Latency 851.682494ms)
May 05 19:44:44 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:44 client: Disconnected
May 05 19:44:44 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:44 client: Connection error: websocket: close 1006 (abnormal clos>
May 05 19:44:44 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:44 client: Retrying in 100ms...
May 05 19:44:45 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:45 client: Connection error: dial tcp [2a04:acc0:18:e::787c:243b]>
May 05 19:44:45 smiley-test.aeza.network chisel[798]: 2024/05/05 17:44:45 client: Retrying in 200ms...
May 05 19:45:19 smiley-test.aeza.network chisel[798]: 2024/05/05 17:45:19 client: Connected (Latency 100.781376ms)
May 05 19:48:19 smiley-test.aeza.network systemd[1]: Stopping Kharej Service 1...
May 05 19:48:19 smiley-test.aeza.network systemd[1]: kharej_1.service: Succeeded.
May 05 19:48:19 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
-- Reboot --
May 05 19:48:32 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 19:48:32 smiley-test.aeza.network chisel[779]: 2024/05/05 19:48:32 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:443
May 05 19:48:35 smiley-test.aeza.network chisel[779]: 2024/05/05 19:48:35 client: Connected (Latency 467.921443ms)
May 05 19:50:07 smiley-test.aeza.network systemd[1]: Stopping Kharej Service 1...
May 05 19:50:07 smiley-test.aeza.network systemd[1]: kharej_1.service: Succeeded.
May 05 19:50:07 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
-- Reboot --
May 05 19:50:18 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 19:50:18 smiley-test.aeza.network chisel[747]: 2024/05/05 19:50:18 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:443
May 05 19:50:19 smiley-test.aeza.network chisel[747]: 2024/05/05 19:50:19 client: Connected (Latency 78.923261ms)
May 05 19:57:07 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:07 client: Disconnected
May 05 19:57:07 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:07 client: Connection error: websocket: close 1006 (abnormal clos>
May 05 19:57:07 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:07 client: Retrying in 100ms...
May 05 19:57:08 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:08 client: Connection error: dial tcp [2a04:acc0:18:e::787c:243b]>
May 05 19:57:08 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:08 client: Retrying in 200ms...
May 05 19:57:08 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:08 client: Connection error: dial tcp [2a04:acc0:18:e::787c:243b]>
May 05 19:57:08 smiley-test.aeza.network chisel[747]: 2024/05/05 19:57:08 client: Retrying in 400ms...
May 05 19:58:02 smiley-test.aeza.network chisel[747]: 2024/05/05 19:58:02 client: ssh: handshake failed: websocket: close 1006 (abnormal>
May 05 19:58:02 smiley-test.aeza.network chisel[747]: 2024/05/05 19:58:02 client: Connection error: ssh: handshake failed: websocket: cl>
May 05 19:58:02 smiley-test.aeza.network chisel[747]: 2024/05/05 19:58:02 client: Retrying in 800ms...
May 05 19:58:48 smiley-test.aeza.network chisel[747]: 2024/05/05 19:58:48 client: Connection error: dial tcp [2a04:acc0:18:e::787c:243b]>
May 05 19:58:48 smiley-test.aeza.network chisel[747]: 2024/05/05 19:58:48 client: Retrying in 1.6s...
May 05 19:58:52 smiley-test.aeza.network chisel[747]: 2024/05/05 19:58:52 client: Connected (Latency 414.230295ms)
May 05 20:00:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 20:00:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 20:00:02 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 20:00:02 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 20:00:02 smiley-test.aeza.network chisel[7174]: 2024/05/05 20:00:02 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:4>
May 05 20:00:02 smiley-test.aeza.network chisel[7174]: 2024/05/05 20:00:02 client: Connection error: read tcp [2a12:5940:9faf::2]:42998->
May 05 20:00:02 smiley-test.aeza.network chisel[7174]: 2024/05/05 20:00:02 client: Retrying in 100ms...
May 05 20:00:03 smiley-test.aeza.network chisel[7174]: 2024/05/05 20:00:03 client: Connected (Latency 420.84649ms)
May 05 20:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 20:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 20:30:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 20:30:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 20:30:01 smiley-test.aeza.network chisel[24166]: 2024/05/05 20:30:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:>
May 05 20:30:02 smiley-test.aeza.network chisel[24166]: 2024/05/05 20:30:02 client: Config verification failed
May 05 20:30:02 smiley-test.aeza.network chisel[24166]: 2024/05/05 20:30:02 client: Retrying in 100ms...
May 05 20:30:07 smiley-test.aeza.network chisel[24166]: 2024/05/05 20:30:07 client: Connected (Latency 644.592623ms)
May 05 21:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 21:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 21:00:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 21:00:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 21:00:01 smiley-test.aeza.network chisel[40899]: 2024/05/05 21:00:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:>
May 05 21:00:02 smiley-test.aeza.network chisel[40899]: 2024/05/05 21:00:02 client: ssh: handshake failed: websocket: close 1006 (abnorm>
May 05 21:00:02 smiley-test.aeza.network chisel[40899]: 2024/05/05 21:00:02 client: Connection error: ssh: handshake failed: websocket: >
May 05 21:00:02 smiley-test.aeza.network chisel[40899]: 2024/05/05 21:00:02 client: Retrying in 100ms...
May 05 21:00:06 smiley-test.aeza.network chisel[40899]: 2024/05/05 21:00:06 client: Connected (Latency 419.65957ms)
May 05 21:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 21:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 21:30:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 21:30:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 21:30:01 smiley-test.aeza.network chisel[57632]: 2024/05/05 21:30:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:>
May 05 21:30:02 smiley-test.aeza.network chisel[57632]: 2024/05/05 21:30:02 client: Connection error: read tcp [2a12:5940:9faf::2]:51688>
May 05 21:30:02 smiley-test.aeza.network chisel[57632]: 2024/05/05 21:30:02 client: Retrying in 100ms...
May 05 21:30:09 smiley-test.aeza.network chisel[57632]: 2024/05/05 21:30:09 client: Connected (Latency 103.641698ms)
May 05 22:00:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 22:00:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 22:00:02 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 22:00:02 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 22:00:02 smiley-test.aeza.network chisel[74342]: 2024/05/05 22:00:02 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:>
May 05 22:00:02 smiley-test.aeza.network chisel[74342]: 2024/05/05 22:00:02 client: ssh: handshake failed: websocket: close 1006 (abnorm>
May 05 22:00:02 smiley-test.aeza.network chisel[74342]: 2024/05/05 22:00:02 client: Connection error: ssh: handshake failed: websocket: >
May 05 22:00:02 smiley-test.aeza.network chisel[74342]: 2024/05/05 22:00:02 client: Retrying in 100ms...
May 05 22:00:04 smiley-test.aeza.network chisel[74342]: 2024/05/05 22:00:04 client: Connected (Latency 740.810093ms)
May 05 22:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 22:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 22:30:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 22:30:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 22:30:01 smiley-test.aeza.network chisel[91075]: 2024/05/05 22:30:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]:>
May 05 22:30:02 smiley-test.aeza.network chisel[91075]: 2024/05/05 22:30:02 client: ssh: handshake failed: websocket: close 1006 (abnorm>
May 05 22:30:02 smiley-test.aeza.network chisel[91075]: 2024/05/05 22:30:02 client: Connection error: ssh: handshake failed: websocket: >
May 05 22:30:02 smiley-test.aeza.network chisel[91075]: 2024/05/05 22:30:02 client: Retrying in 100ms...
May 05 22:30:05 smiley-test.aeza.network chisel[91075]: 2024/05/05 22:30:05 client: Connected (Latency 93.851913ms)
May 05 23:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 23:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 23:00:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 23:00:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 23:00:01 smiley-test.aeza.network chisel[107784]: 2024/05/05 23:00:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 05 23:00:16 smiley-test.aeza.network chisel[107784]: 2024/05/05 23:00:16 client: Connected (Latency 1.529074675s)
May 05 23:00:27 smiley-test.aeza.network chisel[107784]: 2024/05/05 23:00:27 client: Disconnected
May 05 23:00:27 smiley-test.aeza.network chisel[107784]: 2024/05/05 23:00:27 client: Connection error: websocket: close 1006 (abnormal c>
May 05 23:00:27 smiley-test.aeza.network chisel[107784]: 2024/05/05 23:00:27 client: Retrying in 100ms...
May 05 23:00:29 smiley-test.aeza.network chisel[107784]: 2024/05/05 23:00:29 client: Connected (Latency 566.122289ms)
May 05 23:30:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 05 23:30:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 23:30:02 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 23:30:02 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: ssh: handshake failed: websocket: close 1006 (abnor>
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: Connection error: ssh: handshake failed: websocket:>
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: Retrying in 100ms...
May 05 23:30:05 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:05 client: Connected (Latency 731.676164ms)
May 06 00:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 06 00:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 06 00:00:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 06 00:00:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 06 00:00:01 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: ssh: handshake failed: websocket: close 1006 (abnor>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Connection error: ssh: handshake failed: websocket:>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Retrying in 100ms...
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Connection error: dial tcp [2a04:acc0:18:e::787c:24>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Retrying in 200ms...
May 06 00:00:04 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:04 client: Connected (Latency 472.997619ms)
May 06 00:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 06 00:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 06 00:30:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 06 00:30:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 06 00:30:01 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 06 00:30:02 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:02 client: Connected (Latency 79.802222ms)
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Disconnected
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Connection error: websocket: close 1006 (abnormal c>
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Retrying in 100ms...
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Connected (Latency 90.960779ms)
May 06 00:53:21 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 06 00:53:21 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 06 00:53:21 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 06 00:53:21 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 06 00:53:21 smiley-test.aeza.network chisel[171261]: 2024/05/06 00:53:21 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 06 00:53:22 smiley-test.aeza.network chisel[171261]: 2024/05/06 00:53:22 client: Connected (Latency 80.049787ms)
lines 100-134/134 (END)
May 05 23:30:02 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 05 23:30:02 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 05 23:30:02 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: ssh: handshake failed: websocket: close 1006 (abnor>
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: Connection error: ssh: handshake failed: websocket:>
May 05 23:30:02 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:02 client: Retrying in 100ms...
May 05 23:30:05 smiley-test.aeza.network chisel[124498]: 2024/05/05 23:30:05 client: Connected (Latency 731.676164ms)
May 06 00:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 06 00:00:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 06 00:00:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 06 00:00:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 06 00:00:01 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: ssh: handshake failed: websocket: close 1006 (abnor>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Connection error: ssh: handshake failed: websocket:>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Retrying in 100ms...
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Connection error: dial tcp [2a04:acc0:18:e::787c:24>
May 06 00:00:02 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:02 client: Retrying in 200ms...
May 06 00:00:04 smiley-test.aeza.network chisel[141240]: 2024/05/06 00:00:04 client: Connected (Latency 472.997619ms)
May 06 00:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Main process exited, code=killed, status=9/KILL
May 06 00:30:01 smiley-test.aeza.network systemd[1]: kharej_1.service: Failed with result 'signal'.
May 06 00:30:01 smiley-test.aeza.network systemd[1]: Stopped Kharej Service 1.
May 06 00:30:01 smiley-test.aeza.network systemd[1]: Started Kharej Service 1.
May 06 00:30:01 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:01 client: Connecting to ws://[2a04:acc0:18:e:00:00:787c:243b]>
May 06 00:30:02 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:02 client: Connected (Latency 79.802222ms)
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Disconnected
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Connection error: websocket: close 1006 (abnormal c>
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Retrying in 100ms...
May 06 00:30:03 smiley-test.aeza.network chisel[157975]: 2024/05/06 00:30:03 client: Connected (Latency 90.960779ms)

**Comment by Azumi67** [comment]
سلام. سرور شما برای پنج ساعت یا بیشتر مشکل ارتباط handshake داشته و پینگ اتصال هم 600 بوده که معمولا روی 80 هست. ریست تایمر سرور‌ایران و سرور خارج شما به نظر با هم فرق دارن و اینکه از آی‌پی 6 استفاده کردید . شما میتونید از یکی از روش های لوکال آی‌پی استفاده کنید و ببینید باز هم چنین اختلالی دارید یا خیر. حتی میتونید سرور‌خارج دیگری رو با اون سرور ایران تست کنید که ببینید مشکل حل میشه یا اختلال از سوی خود سرور‌ایران هست.

**Comment by pouriasharifzad** [comment]
ممنونم
میتونم با gre لوکال بسازم با چیزل تانل کنم یا باید از گاست استفاده کنم حتما؟

**Comment by Azumi67** [comment]
بله میتونید و همچنین میتونید گوست یا هر تانلی دیگری‌ که براتون بهتر جواب میده استفاده کنید و اینکه فقط نیازه یکی از optimizer ها رو نصب کنید .
