### ISSUE TITLE
نسبت آپلود / دانلود

### ISSUE THREAD

**Issue by pouriasharifzad** [Azumi67/Chisel_multipleServers#33]
سلام با آی پی لوکال 6to4 و تانل چیزل کانکت شدم و نسبت دانلود همیشه دو برابر آپلود هست توی سرور ایران این طبیعیه؟

**Comment by Azumi67** [comment]
سلام بسته به نوع encapsulation می‌تونه تا 1.4 هم بالا بره و هم چنین خود تانل اگر‌ ریورس باشه هم بالاتر می‌بره .
