### ISSUE TITLE
توکن دار کردن

### ISSUE THREAD

**Issue by mehranweb** [Azumi67/Chisel_multipleServers#34]
سلام 
وقت بخیر
ابتدا ممنون از زحمات بی دریغ تان
می خواستم بگم اگر این تانل هم مثل رتهول، یه پسوردی رو بشه برایش قرار داد باعث افزایش امنیت میشه.

**Comment by Azumi67** [comment]
سلام مرسی. این تانل از keygen استفاده می‌کنه و به صورت رندوم براتون قرار میده.
