### ISSUE TITLE
چرا پنل سنایی در سرور ایران نمایش داده نمیشه

### ISSUE THREAD

**Issue by MahdiMadhani** [Azumi67/Chisel_multipleServers#35]
سلام
روش ریورس تانل - ایپی 4 - TCP - تک سرور رو انجام دادم اوکی هستش فقط باید بریم به صورت دستی سرور ایران رو جایگزین سرور خارج کنیم
لطفا  بفرمایید باید چه کاری انجام دهیم که پنل در سرور ایران( سرورایران پشت دامنه هستش)  نمایش داده بشه 
باتشکر

**Comment by Azumi67** [comment]
سلام. اگر منظورتون اینه که پنل با آی‌پی ایران هم بالا بیاید که باید پورت پنل را هم به سمت آی‌پی ایران فوروارد کنید .

**Comment by MahdiMadhani** [comment]
> سلام. اگر منظورتون اینه که پنل با آی‌پی ایران هم بالا بیاید که باید پورت پنل را هم به سمت آی‌پی ایران فوروارد کنید .

تشکر درست شد
