### ISSUE TITLE
حداکثرتعداد پورت ها در Chisel

### ISSUE THREAD

**Issue by MahdiMadhani** [Azumi67/Chisel_multipleServers#36]
سلام ما ازReverseTlsTunnel  استفاده کردیم و برای هر کاربر ی پورت ایجاد کردیم و تعداد پورت ها الان ۲۰۰ پورت هستن
الان میخوایم از Chisel تانل استفاده کنیم
میتونیم از ۲۰۰ پورت استفاده کنیم؟
حداکثرتعداد پورت چندتا هستش
ممنون

**Comment by Azumi67** [comment]
سلام. تانل آقای رادکسوت امکان فوروارد تعداد پورت زیاد و رنج پورت داره اما چیزل تعداد محدودی را میتوانید فوروارد کنید . بهتره از همون تانل آقای رادکسوت استفاده کنید .

**Comment by MahdiMadhani** [comment]
> سلام. تانل آقای رادکسوت امکان فوروارد تعداد پورت زیاد و رنج پورت داره اما چیزل تعداد محدودی را میتوانید فوروارد کنید . بهتره از همون تانل آقای رادکسوت استفاده کنید .

تانل آقای رادکسوت قطعی داره. 
لطفا بفرمایید حداکثرچه تعداد پورت میشه  فوروارد کرده

**Comment by Azumi67** [comment]
من تا ده تا تست کردم . شما‌ پنل به پنل هم تست کنید . رت هول هم میتونید تست کنید .

**Comment by MahdiMadhani** [comment]
> من تا ده تا تست کردم . شما‌ پنل به پنل هم تست کنید . رت هول هم میتونید تست کنید .

تشکر
