### ISSUE TITLE
قطعی 

### ISSUE THREAD

**Issue by MahdiMadhani** [Azumi67/Chisel_multipleServers#37]
سلام
  بعداز قطع  باید   restart   شود

apt-daily.service                             graphical.target.wants       sleep.target.wants
apt-daily-upgrade.service                   kharej_1.service             sockets.target.wants
dbus-org.freedesktop.ModemManager1.service  kharej_2.service             sshd.service
dbus-org.freedesktop.resolve1.service       mdmonitor.service.wants      sudo.service
dbus-org.freedesktop.thermald.service       multi-user.target.wants      sysinit.target.wants
dbus-org.freedesktop.timesync1.service      network-online.target.wants  syslog.service
display-manager.service.wants               oem-config.service.wants     timers.target.wants
emergency.target.wants                      paths.target.wants           tunnel.service
getty.target.wants                          rescue.target.wants          x-ui.service

**Comment by Azumi67** [comment]
سلام. شما دو تا سرویس خارج دارید. اول اینکه مطمئن بشید که داخل cronrab دستورات ریست هست و اجرا میشن. از طریق journalctl هم بررسی کنید که ریست انجام شده یا نه . مورد دیگر اینکه لاگ های تانل را در هنگام خطا ببینید . مورد مهمی که هست اینه که وقتی سرور ایران شما مشکل داشته باشه ، هیچ تانلی نمیتونه برای شما بهینه کار کنه. تمام این مورد ها‌ را بررسی کنید . باید در نظر داشته باشید که الان مدتی هست که تانل های ریورس روی بعضی از سرور ها اختلال دارند.

**Comment by MahdiMadhani** [comment]
سرور rebuild  کردم و مراحل از اول رفتم چرا دوتا سرویس خارج هستش؟
apt-daily.service                           graphical.target.wants       sleep.target.wants
apt-daily-upgrade.service                   kharej_1.service             sockets.target.wants
dbus-org.freedesktop.ModemManager1.service  kharej_2.service             sshd.service
dbus-org.freedesktop.resolve1.service       mdmonitor.service.wants      sudo.service
dbus-org.freedesktop.thermald.service       multi-user.target.wants      sysinit.target.wants
dbus-org.freedesktop.timesync1.service      network-online.target.wants  syslog.service
display-manager.service.wants               oem-config.service.wants     timers.target.wants
emergency.target.wants                      paths.target.wants           x-ui.service
getty.target.wants                          rescue.target.wants

**Comment by Azumi67** [comment]
چون دو تا کانفیگ (پورت ) دارید . با status بررسیشون کنید .

**Comment by MahdiMadhani** [comment]
یکی برای پورت پنل هستش یکی هم برای کانفیگ ها
مورد زیر رو باید چطور بررسی کنم
 داخل cronrab دستورات ریست هست و اجرا میشن

**Comment by Azumi67** [comment]
systemctl status kharej_1.service
systemctl status kharej_2.service
اینجا فقط نفرستید که آی‌پی هاتون معلوم خواهد بود

**Comment by MahdiMadhani** [comment]
به جای ip زدم ***
● kharej_1.service - Kharej Service 1
     Loaded: loaded (/etc/systemd/system/kharej_1.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-06-03 20:00:02 UTC; 12min ago
   Main PID: 3035 (chisel)
      Tasks: 7 (limit: 1037)
     Memory: 293.1M
        CPU: 1min 15.144s
     CGroup: /system.slice/kharej_1.service
             └─3035 /root/./chisel client --keepalive 10s ***:443 R:localhost:24211

Jun 03 20:00:02 localhost systemd[1]: Started Kharej Service 1.
Jun 03 20:00:02 localhost chisel[3035]: 2024/06/03 20:00:02 client: Connecting to ws://***:443
Jun 03 20:00:03 localhost chisel[3035]: 2024/06/03 20:00:03 client: ssh: handshake failed: websocket: clo>
Jun 03 20:00:03 localhost chisel[3035]: 2024/06/03 20:00:03 client: Connection error: ssh: handshake fail>
Jun 03 20:00:03 localhost chisel[3035]: 2024/06/03 20:00:03 client: Retrying in 100ms...
Jun 03 20:00:04 localhost chisel[3035]: 2024/06/03 20:00:04 client: Connected (Latency 106.419952ms)

**Comment by Azumi67** [comment]
خطای هندشیک داده . اگر آی‌پی ۴ هست ، از لوکال آی‌پی استفاده کنید یا آی‌پی ۶ native.

**Comment by MahdiMadhani** [comment]
بله آی‌پی ۴ هست.
چطور از لوکال آی‌پی استفاده کنیم

**Comment by MahdiMadhani** [comment]
بله آی‌پی ۴ هست.
چطور از لوکال آی‌پی استفاده کنیم

**Comment by Azumi67** [comment]
یا به صورت manual یا اسکریپت, یکی از روش های لوکال‌ ایپی را ایجاد میکنید و بعد با اون آی‌پی، تانل را انجام می‌دهید .
برای اسکریپت یا میتونید از اسکریپت من استفاده کنید یا از مدل های دیگر که در گیت هاب موجود است یا یه صورت manual ایجاد کنید . تفاوتی ندارند.

**Comment by MahdiMadhani** [comment]
ممنون از راهنماییتان
لطفا بفرمایید چطور با  اسکریپت من انجام بدیم

**Comment by Azumi67** [comment]
آموزش داره بخونید .
https://github.com/Azumi67/6TO4-GRE-IPIP-SIT

**Comment by MahdiMadhani** [comment]
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/6TO4-GRE-IPIP-SIT/main/ubuntu24.sh)"
در اسکریپت بالا برای 
Single Server MENU 
قسمت Choose what to do: 
باید کدوم یک از گزینه ها رو انتخاب کنیم؟
1. Extra Native IPV6
2. Edit MTU
3. Geneve UDP 
4. Geneve + IPsec
5. ICMP + IPsec
42.ERSPAN [test][Some of them will be removed]
6. IP6IP6
7. IP6IP6 + IPSec
8. Private IP
9. Private IP + IPSec
10. GRE
11. GRE6
12. GRE6 + IPSec
13. GRE6tap
14. GRE6tap + IPSec
15. 6TO4 
16. 6TO4 [Anycasnt]

**Comment by Azumi67** [comment]
هر کدوم که برای شما کار میکنه. اموزش ها رو بخونید. ممکنه نتونم جواب بدم و باید درس بخونم
