### ISSUE TITLE
تغییر تایم ریست سرور ایران

### ISSUE THREAD

**Issue by SAEIDKHANDANI** [Azumi67/Chisel_multipleServers#39]
سلام وقت بخیر

لطفا روش تغییر تایم ریست سرور ایران رو قرار بدید نیم ساعت خیلی زمان کمیه و توی دانلود فایل یا آپلود فایل دچار مشکل میشه و دانلود یا آپلود کنسل میشه 

دمتون گرم

**Comment by Azumi67** [comment]
سلام. داخل خود اسکریپت ویرایش ادیت این مورد وجود دارد. از اون طریق میتوانید هر تایمی که دوست داشتید قرار بدهید.
