### ISSUE TITLE
روی ubuntu 24 کار نمیکنه

### ISSUE THREAD

**Issue by SasanKHZN** [Azumi67/Chisel_multipleServers#40]
سلام ازومی عزیز
این یکی از بهترین اسکریپت ها هستش ممنون که توسعه دادی فقط یک موردی داره روی ubuntu 24 به هیچ عنوان کار نمیکنه اسکریپتها اجرا نمیشن

**Comment by Azumi67** [comment]
سلام مرسی. باشه یادم نبود . باید یک اپدیت برای این مورد بدم
