### ISSUE TITLE
cron در سرور ایران اینستال نمیشه و تانل کار نمیکنه

### ISSUE THREAD

**Issue by SasanKHZN** [Azumi67/Chisel_multipleServers#41]
سلام ازومی
cron در سرور ایران اینستال نمیشه و کار نمیکنه البته مشکل از سرور نیست چون به صورت دستی اینستال میشه خواستم فقط اطلاع بدم

**Comment by Azumi67** [comment]
سلام سرور های ایران زیادی تست کردم که مشکلی نبوده . فوقش بعدا برای کرون یک برنامه جدا می‌نویسم هر وقت آزادتر بودم .
به هر حال مرسی
