### ISSUE TITLE
سوال در مورد تانل های شما

### ISSUE THREAD

**Issue by lostsoul6** [Azumi67/Chisel_multipleServers#42]
درود @Azumi67 وقت بخیر .

خواستم بدونم از میان تانل های شما ، کدوم این قابلیت رو دارن که تعداد کانکشن های رد و بدل شده بین سرور ایران و خارج رو کاهش بدن؟ اسکریپت آقای رادکسوت رو چک کردم ، گزینه های mux و concurrency جالب بود . خواستم بدونم در بین تانل های شما هم چنین قابلیتی هست ؟ 

تشکر

**Comment by Azumi67** [comment]
سلام. بیشترشون فکر میکنم چنین قابلیت هایی دارند .

**Comment by lostsoul6** [comment]
خودتون کدوم رو پیشنهاد میدید که این قابلیت رو داشته باشه حتما ؟ و اینکه چطور فعال میشه ؟ توی اسکریپت شما امکان فعال کردن و تغییر مقادیرش هست یا باید document های سورس رو ببینیم و دستی اوکی کنیم ؟ تشکر

**Comment by Azumi67** [comment]
بیشترشون به صورت دیفالت دارند . به نظرم پروژه جدید آقای رادکسوت بهتره .
