### ISSUE TITLE
وایرگارد udp کارنمیکنه

### ISSUE THREAD

**Issue by m0x61h0x64i** [Azumi67/Chisel_multipleServers#43]
سلام، تانل زدم متاسفانه وایرگارد هندشیک نمیده. وایرگارد داکرایز شده و پورت و ایناش اوکی هست مستقیم اگر وصل بشم هندشیک میده

روی سرور ایران 2 رو زدم و پورت تانل 2096 دادم

روی سرور خارج 2 رو زدم و اینکار هارو کردم:
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/109550653/95d28358-4fe4-4640-bd06-b61f4f2f1404)

داخل کلاینت پورت 22355 استفاده میشه و داکر هم به پورت 22355 udp لیسن میکنه:
docker ports => 0.0.0.0:22355->22355/udp, :::22355->22355/udp

کسی میدونه مشکل از چی میتونه باشه؟

با nginx روی ایران تانل میزنم اوکی هست ولی چیزل اوکی نیست و حالا سعی کردم با nginx ور برم درستش کنم هم بازم فایده نکرد

**Comment by Azumi67** [comment]
سلام . شما یک بار با لوکال ایپی هم همین کار رو بکنید و ببینید ایا با اون این مشکل حل میشه یا خیر.روش های مختلف لوکال ایپی را تست بفرمایید

**Comment by m0x61h0x64i** [comment]
اشنایی ندارم میشه یه روش ریورس لوکال پیشنهاد کنید؟

**Comment by Azumi67** [comment]
شما اول از طریق این لینک آموزش رو بخونید و یک لوکال مثلا vxlan را کانفیگ کنید و حالا دوباره تانل انجام دهید .
https://github.com/Azumi67/6TO4-GRE-IPIP-SIT

**Comment by m0x61h0x64i** [comment]
روی هردو سرور ایران و خارج مطابق "روش Vxlan با IPsec به صورت P2P" رفتم و پیغام 
✨ Vxlan P2P /W IPSEC Configured
رو دریافت کردم. اومدم بیرون با دستور
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/chisel.sh)"
تانل چیزل رو روی پورتی که توی روش بالا وارد کردم رو اینجا هم واردکردم

پورت کانفیگ هم یه پورت جدا از پورت تانل یعنی 22355 دادم

ولی متاسفانه کانفیگ وایرگارد کارنمیکنه

**Comment by m0x61h0x64i** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/issues/352
https://github.com/Musixal/Rathole-Tunnel/issues/22

**Comment by Azumi67** [comment]
شما دقیقا مطمئن شدید که دو پرایوت آی‌پی vxlan به هم پینگ دارن و از همون پرایوت آی‌پی ها یه جای آی‌پی مورد نیاز در چیزل استفاده کردید ؟ به طور مثال اگر آی‌پی خروجی ۶ هست ، در قسمت آی‌پی ۶ چیزل آی‌پی رو وارد میکنید . در vxlan باید فایروال هم بررسی کنید ‌

**Comment by m0x61h0x64i** [comment]
خروجی سرور ایران:
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/109550653/132a2735-cb83-4462-ba2c-4d8d4250e9ad)

خروجی سرور خارج:
![image](https://github.com/Azumi67/Chisel_multipleServers/assets/109550653/0a31d68a-e3c5-48b0-a9e9-b64544acf373)
به نظر میاد پینگ نمیدن حالا من نمیدونم منظورتون از پینگ دقیقا چیه.
فایروال هردو خاموشه.

> از همون پرایوت آی‌پی ها یه جای آی‌پی مورد نیاز در چیزل استفاده کردید ؟

خیر. اطلاع نداشتم. شما منظورتون از پینگ رو بگین من برم اونو اوکی کنم بعد برم توی چیزل از پرایوت ایپی استفاده کنم.

**Comment by Azumi67** [comment]
باید هر دو سمت بهم پینگ بدن . بررسی کنید که چرا پینگ نمیدن . روش های مختلف لوکال تست کنید .

**Comment by m0x61h0x64i** [comment]
قاعدتا اگر توی سرور ایران از سرور خارج پینگ بگیرم یا برعکس حتی بدون تانل هم پینگ میدن، منظورتون در شرایط دیگه ای هست؟ بیشتر توضیح میدین؟

یه روش لوکال بگین من برم تست کنم

**Comment by Azumi67** [comment]
داخل اسکرین شاتی که دادید لوکال‌ایپی های شما به هم دیگه پینگ ندارند . برای این گفتم .

**Comment by m0x61h0x64i** [comment]
ببینید اصن غیر از روش های دیگه و مسائل دیگه. همین تانل چیزل که من میزنم با tcp کانفیگ v2ray اوکی هست ولی با udp وایرگارد کار نمیکنه. حالا شما میگین مشکل از چیزله باید یه روش دیگه ای رو با این ترکیب کنم؟

**Comment by Azumi67** [comment]
> ببینید اصن غیر از روش های دیگه و مسائل دیگه. همین تانل چیزل که من میزنم با tcp کانفیگ v2ray اوکی هست ولی با udp وایرگارد کار نمیکنه. حالا شما میگین مشکل از چیزله باید یه روش دیگه ای رو با این ترکیب کنم؟

ببینید ممکنه از خود داکر هم باشه . یادمه یکی بود وایرگارد داکر رو نمیتونست با udp2raw استفاده کنه . خودم قبلا چند سال پیش، وایرگارد داکر رو به صورت مستقیم و هم تانل استفاده میکردم. اما تا تست نکنید روش های مختلف رو نمیشه متوجه شد مشکل از کجاست و اینطوری هم سخته من بفهمم که مشکل از کجاست . منظورم اینه که باید تست های زیادی انجام بدید .
