### ISSUE TITLE
علت بالا نیامدن پنل ایران بعد از تانلینگ مستقیم 

### ISSUE THREAD

**Issue by BenyaminMoadab** [Azumi67/Chisel_multipleServers#44]
من یک سرور در ایران دارم و یکی در آلمان و از ساب اسکریبشن استفاده میکنم برای اکانت هام اما این تانل متاسفانه پنل سرور ایران را بالا نمیاورد و ساب اسکریبشن کار نمیکند
راهکاری هست؟

**Comment by Azumi67** [comment]
پورت پنل و آی‌پی ایران هم فوروارد کنید . فکر میکنم بقیه هم همینطوری مشکلشون رو حل کردند .

**Comment by BenyaminMoadab** [comment]
یعنی موقعی که داره پورت کانفیگ میگیره تو اسکریپت 
پورت پنل رو هم به عنوان پورت کانفیگ وارد کنم؟

**Comment by Azumi67** [comment]
بله
