### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by MahdiMadhani** [Azumi67/Chisel_multipleServers#46]
سلام برای نصب به صورت ipv6 local مراحل رو انجام دادم وضعیت تانل به صورت فعال هستش
تعریف ipv6 به صورت زیر 
nano /etc/systemd/network/tun0.network
سرور ایران
[Network]
Address=fd12:3556:7790:abcd::2/64
Gateway=fd12:3556:7790:abcd::1

 پینگ به سرور ایران در سرور خارج
ping fd12:3556:7790:abcd::2
PING fd12:3556:7790:abcd::2(fd12:3556:7790:abcd::2) 56 data bytes
64 bytes from fd12:3556:7790:abcd::2: icmp_seq=1 ttl=64 time=92.4 ms
64 bytes from fd12:3556:7790:abcd::2: icmp_seq=2 ttl=64 time=89.6 ms

 ولی در سرور خارج خطای زیر رو نشون میده
systemctl status kharej_1.service
● kharej_1.service - Kharej Service 1
     Loaded: loaded (/etc/systemd/system/kharej_1.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-07-16 13:30:02 UTC; 5min ago
   Main PID: 84346 (chisel)
      Tasks: 6 (limit: 1037)
     Memory: 2.7M
        CPU: 29ms
     CGroup: /system.slice/kharej_1.service
             └─84346 /root/./chisel client --keepalive 10s "[fd12:3556:7790:abcd::2]:5000" R:localhost:24>

Jul 16 13:30:20 localhost chisel[84346]: 2024/07/16 13:30:20 client: Connection error: server: Server can>
Jul 16 13:30:20 localhost chisel[84346]: 2024/07/16 13:30:20 client: Retrying in 12.8s...
Jul 16 13:30:34 localhost chisel[84346]: 2024/07/16 13:30:34 client: Connection error: server: Server can>
Jul 16 13:30:34 localhost chisel[84346]: 2024/07/16 13:30:34 client: Retrying in 25.6s...
Jul 16 13:31:00 localhost chisel[84346]: 2024/07/16 13:31:00 client: Connection error: server: Server can>
Jul 16 13:31:00 localhost chisel[84346]: 2024/07/16 13:31:00 client: Retrying in 51.2s...
Jul 16 13:31:52 localhost chisel[84346]: 2024/07/16 13:31:52 client: Connection error: server: Server can>
Jul 16 13:31:52 localhost chisel[84346]: 2024/07/16 13:31:52 client: Retrying in 1m42.4s...
Jul 16 13:33:35 localhost chisel[84346]: 2024/07/16 13:33:35 client: Connection error: server: Server can>
Jul 16 13:33:35 localhost chisel[84346]: 2024/07/16 13:33:35 client: Retrying in 3m24.8s...

**Comment by Azumi67** [comment]
سلام. کاملا مشخص نیست شما چگونه کانفیگ چیزل رو انجام دادید . اگر مطمئن هستید که درست انجام دادید،‌ اطمینان پیدا کنید که آی‌پی فوروارد هم فعال هست و همچنین اگر بازم جواب نداد یکبار با آی‌پی ۴ یا ۶ خود سرور هم تست کنید تا ببینید مشکل از کجا است.

**Comment by MahdiMadhani** [comment]
sudo apt-get install python3 -y && apt-get install wget -y && apt-get install python3-pip -y && pip3 install colorama && pip3 install netifaces && apt-get install curl -y && python3 <(curl -Ls https://raw.githubusercontent.com/Azumi67/Chisel_multipleServers/main/chisel.py --ipv4)

با اموزش https://www.youtube.com/watch?v=AjNrYOpNaQE جلو رفتم
گزینه 1. Chisel TCP [IPV4]  به صورت کامل ایجاد شد

cd /etc/systemd/system
root@localhost:/etc/systemd/system# ls
apt-daily.service                           kharej_1.service             rescue.target.wants
apt-daily-upgrade.service                   kharej_2.service             sleep.target.wants
dbus-org.freedesktop.ModemManager1.service  kharej_3.service             sockets.target.wants
dbus-org.freedesktop.resolve1.service       kharej_4.service             sshd.service
dbus-org.freedesktop.thermald.service       kharej_5.service             sudo.service
dbus-org.freedesktop.timesync1.service      mdmonitor.service.wants      sysinit.target.wants
display-manager.service.wants               multi-user.target.wants      syslog.service
emergency.target.wants                      network-online.target.wants  timers.target.wants
getty.target.wants                          oem-config.service.wants     tunnel.service
graphical.target.wants                      paths.target.wants           x-ui.service
root@localhost:/etc/systemd/system# systemctl status kharej_2.service
● kharej_2.service - Kharej Service 2
     Loaded: loaded (/etc/systemd/system/kharej_2.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-07-16 16:27:03 UTC; 1min 31s ago
   Main PID: 4130 (chisel)
      Tasks: 6 (limit: 1037)
     Memory: 2.5M
        CPU: 9ms
     CGroup: /system.slice/kharej_2.service
             └─4130 /root/./chisel client --keepalive 10s  iranip:443 R:localhost:27032

Jul 16 16:27:07 localhost chisel[4130]: 2024/07/16 16:27:07 client: Connection error: unexpected EOF (Att>
Jul 16 16:27:07 localhost chisel[4130]: 2024/07/16 16:27:07 client: Retrying in 3.2s...
Jul 16 16:27:11 localhost chisel[4130]: 2024/07/16 16:27:11 client: Connection error: unexpected EOF (Att>
Jul 16 16:27:11 localhost chisel[4130]: 2024/07/16 16:27:11 client: Retrying in 6.4s...
Jul 16 16:27:17 localhost chisel[4130]: 2024/07/16 16:27:17 client: Connection error: unexpected EOF (Att>
Jul 16 16:27:17 localhost chisel[4130]: 2024/07/16 16:27:17 client: Retrying in 12.8s...
Jul 16 16:27:30 localhost chisel[4130]: 2024/07/16 16:27:30 client: Connection error: unexpected EOF (Att>
Jul 16 16:27:30 localhost chisel[4130]: 2024/07/16 16:27:30 client: Retrying in 25.6s...
Jul 16 16:27:56 localhost chisel[4130]: 2024/07/16 16:27:56 client: Connection error: unexpected EOF (Att>
Jul 16 16:27:56 localhost chisel[4130]: 2024/07/16 16:27:56 client: Retrying in 51.2s...
lines 1-20/20 (END)Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.0-25-generic x86_64)

**Comment by Azumi67** [comment]
اینکه eof داده . یا یک جا اشتباه کردید یا امکان تانل برای شما بوسیله لوکال‌ آی‌پی توسط چیزل در سرور ایرانتون امکان پذیر نیست .شما باید چندین کار کنید . با همون لوکال‌ایپی ها سعی کنید پورت فوروارد کنید و ببینید بازم جواب میده یا خیر . توسط چیزل با ایپی ۴ و ۶ سرور تانل‌ رو برقرار کنید و ببینید بازم جواب میده یا خیر. اینطوری میشه فهمید که آیا مشکل کانفیگ کردن شما هست یا موردی در سرور شما هست

**Comment by MahdiMadhani** [comment]
از سرور خارج به سرور ایران و برعکس وقتی از روی ipv6 لوکال پینگ میگیرم پینگ داره
ping fd12:3556:7790:abcd::1

**Comment by Azumi67** [comment]
> از سرور خارج به سرور ایران و برعکس وقتی از روی ipv6 لوکال پینگ میگیرم پینگ داره ping fd12:3556:7790:abcd::1

بله میتونید پینگ هم داشته باشید اما بازم تانل، نتواند اتصالی برقرار کند.

**Comment by MahdiMadhani** [comment]
چنتا سرور دارم با تنظیمات یکسان و با تانل شما اوکی هستن فقط یکی از سرورها مشکل داره همه سرورها خارج از یک جا خریدم 
با ip a سرورها رو مقایسه کردم فقط همین سرور قسمت زیر رو اضافه داره
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
 
ایا 3: sit0@NONE  میتونه باعث این مشکل بشه؟ 

ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:16:67:6d:91:06 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet ***/24 metric 100 brd ****.255 scope global dynamic eth0
       valid_lft 2575072sec preferred_lft 2575072sec
    inet6 fe80::216:67ff:fe6d:9106/64 scope link 
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
