### ISSUE TITLE
اشکال

### ISSUE THREAD

**Issue by mehdi1x1** [Azumi67/Chisel_multipleServers#5]
در پرایوت تانل tcp وقتی سرور خارج ریست میشه کل پورت ها می پره.از دوباره وارد شه.یه گزینه برای ali port بزارید

**Comment by mehdi1x1** [comment]
مهندس اگه امکانش هست یه دستور برای start up بنویسید ریست میشه تانل قطع نشه

**Comment by Azumi67** [comment]
> در پرایوت تانل tcp وقتی سرور خارج ریست میشه کل پورت ها می پره.از دوباره وارد شه.یه گزینه برای ali port بزارید

سلام. یعنی چی کل پورت ها میپره ؟ حالا دوباره خودم وقت کنم، نگاه میکنم. در مورد ریست تایمر هم ، داخل برنامم هست که اضافش کنم. باید برای تمام سرویس ها اضافه بشه.

**Comment by mehdi1x1** [comment]
یعنی سرور ریست شه تانل کلا قطع میشه دوباره باید تانل بزنیم و پورت ها دوباره وارد شه

**Comment by Azumi67** [comment]
مرسی که اطلاع دادید. مشکل الان باید حل شده باشه. تست کنید.

**Comment by mehdi1x1** [comment]
ممنون ازتون.امکان گزینه همه پورت ها وجود نداره؟چون با پورت مختلف کانفیگ ارائه شده

**Comment by Azumi67** [comment]
در حال حاضر خیر . بعدا اون ریست تایمر هم اضافه میکنم کمی وقتم ازادتر بشه .
