### ISSUE TITLE
ترکیب با دکودمودور

### ISSUE THREAD

**Issue by saedgholami** [Azumi67/Chisel_multipleServers#6]
با عرض سلام و خسته نباشید
![chisel](https://github.com/Azumi67/Chisel_multipleServers/assets/154999714/d5afb368-a64e-480b-a904-1d0fff6195de)
![chisel1](https://github.com/Azumi67/Chisel_multipleServers/assets/154999714/17fc8d4d-3aae-490d-8c5d-5c6bba2edb29)
من 2 کانفیگ به چیسل معرفی کردم . که روی پورت 443 از طریق دکو قبلا تانل زدم به سرور ایران ، میخواستم بدونم که آیا چیسل به طور اتوماتیک روی پورت 443 و دکو سوار میشه یا اینکه اختلال ایجاد میکنه؟ یا اینکه اصلا فعال نمیشه و روی دکو تاثیری نمیذاره؟ امیدوارم تونسته باشم سوالم رو درست پرسیده باشم و مفهوم رسونده باشم
با تشکر از زحمات شما

**Comment by Azumi67** [comment]
سلام.مرسی. ببینید وقتی پورتی درگیر باشه دیگر نمیشه اون پورت رو برای تانل دیگری استفاده کرد. شما باید پورت دیگری استفاده کنید

**Comment by saedgholami** [comment]
خب من روی پورت 8011 هم فعال کردم که داره کار میکنه، ولی نکته ای که هست اینه که کانفیگ های روی پورت 8011 که ست کردم هدر اضافه میکنم قطع میشه و بدون هدر پینک میده ، و نکته بعدی اینکه کانفیگ های روی پورت 8011 فقط روی آیپی ایرانم پینگ میده و روی آیپی یا ساب دامین سرور خارج پینک ندارم که در هرصورت من ساب دامین که روی آیپی ایران زدم استفاده میکنم که کار میکنه ، خواستم بدونم که این مورد طبیعی هست یا جایی رو اشتباه رفتم مخصوصا قضیه هدر 
با تشکر

**Comment by Azumi67** [comment]
> خب من روی پورت 8011 هم فعال کردم که داره کار میکنه، ولی نکته ای که هست اینه که کانفیگ های روی پورت 8011 که ست کردم هدر اضافه میکنم قطع میشه و بدون هدر پینک میده ، و نکته بعدی اینکه کانفیگ های روی پورت 8011 فقط روی آیپی ایرانم پینگ میده و روی آیپی یا ساب دامین سرور خارج پینک ندارم که در هرصورت من ساب دامین که روی آیپی ایران زدم استفاده میکنم که کار میکنه ، خواستم بدونم که این مورد طبیعی هست یا جایی رو اشتباه رفتم مخصوصا قضیه هدر با تشکر

شما همونطور که بهتون گفتم ،سعی کنید از یکیشون استفاده کنید که اختلال پیش نیاد.
