### ISSUE TITLE
نوع تانل 

### ISSUE THREAD

**Issue by eylandoo** [Azumi67/Chisel_multipleServers#7]
سلام و خسته نباشید
مهندس جان
آیا این تانل از خارج به ایران هست؟
و در صورت ip private
و ریورس
آیا امکان داره باز سرور خارج رو بزنن..؟

**Comment by Azumi67** [comment]
سلام . مرسی . این ریورس تانل هست ، سرور، ایران میشه و کلابنت، خارج
سرور فیلتر شده باید در این تانل جواب بده. یعنی حتی اگر سرور خارجتون فیلتر هم شده باشه، باید باز هم در این تانل، بتونید جواب بگیرید. شما مدل های مختلف رو تست کنید و ببینید کدوم به شما بهترین جواب رو میده.
