### ISSUE TITLE
ios 

### ISSUE THREAD

**Issue by eylandoo** [Azumi67/Chisel_multipleServers#8]
مهندس همچی خوبه
ولی ی نکته من خودم اندروید هستم مشکلی ندیدم
اما یکسری ios ها
با هر برنامه ایی که بگین یکسری قطع و وصلی ها دارن پشت هم
راهکاری هست براشون؟

**Comment by Azumi67** [comment]
من خودم از ایفون استفاده میکنم و با وایرگارد مشکلی نداشتم ولی سایرشون رو داخل ایفون تست نکردم. باید از کسانی که تجربه بیشتری دارند سوال کنید

**Comment by eylandoo** [comment]
مهندس دلیل خاصی داره که خودتون از x-ui استفاده نمی‌کنید؟
آیا وایرگارد برای فروش خوبه؟ با توجه ب اینکه از یک پورت استفاده می‌کنه

**Comment by Azumi67** [comment]
راستش مهندس هنوز نیستم و باید درس بخونم xD میتونید منو ازومی صدا کنید . اما جدای از شوخی ، با وایرگارد روی ایفون راحتم و اینکه برای گیم هام ارش استفاده میکنم. xui هم خیلی قویه و خیلی ها راضین. 
من چون فروشنده نیستم، نمیتونم راهنمایی کنم . میشه روی یک پورت چندین peer وصل بشن ، مشکلی نیست.

**Comment by eylandoo** [comment]
از نظر من شما یک مهندس هستین
ولی در کل استفاده از یک پورت رو فقط برای این گفتم که شناسایی سرور خارج لو نره
یا در این روش نهایت ایران اکسس نشه
