### ISSUE TITLE
اسپید تست

### ISSUE THREAD

**Issue by mehradsiminfar** [Azumi67/Chisel_multipleServers#9]
با مراجعه به سایت اسپید تست ارتباط قطع میشه
این لاگ رو کجا باید نگاه کنم؟
و اینکه دستور نمایش خود اسکریپت چیه؟

**Comment by Azumi67** [comment]
سلام. وارد سایت اسپید تست بشید و وقتی قطع شد این دستورات هم ببینید
cd /etc/systemd/system
ببینید نام سرویستون چیه.و نام سرویس رو با اون نام سرویس خودتون پر کنید
systemctl status نام سرویس
journalctl -u نام.service
بعد متن را کامل کپی گنید و بفرستید. هم ایران و هم خارج.
یک کاره دیگه هم بکنید. وقتی تست سرعت میگیرید ببینید xui شما هم داره کار میکنه یا خیر. از داخل پنل status ش رو بررسی کنید و هم چنین ببینید پس از قطغ ارتباط تانل، بازم میتونید به صورت مستقیم هم وصل بشید یا اونم قطع میشه.

**Comment by Azumi67** [comment]
من خودم با روش های مختلف و تغییرات مختلف تست کردم ؛ متاسفانه دیدم که با اسپید تست کانکشن قطع میشد و بعد از چند ثانیه وصل میشد. صبح هم ببینم چنین مشکلی هست یا خیر. چون یادمه صبح من تست کرده بودم و خوب بود.

**Comment by Azumi67** [comment]
تست سرعت در صبح هم انجام شد و کاملا بدون مشکل و قطع شدن ارتباط. این مشکل به نظر در شب اتفاق میوفته و این نمیتونه مشکل از تانل باشه.
